### ISSUE TITLE
Rahel: Week 4,Separation of Concerns

### ISSUE THREAD

**Issue by Rahela-HYF** [HackYourFutureBelgium/class-7#100]
#### What is JavaScript?
>- [x] Andrew Mosh
>- [x] Code School
>- [x] MDN: First Steps
>- [x] MDN: JS Basics
>- [x] javascript.info
#### Write some Code
>- [x] Including JS in HTML
>- [x] Using JS DevTools
>- [x] Rules for writing JS
>- [x] Start learnjavascript.online through 2. Strings

### Project: calculator-refactor
[repo](https://github.com/Rahela-HYF/calculator-refactor)   [live](https://rahela-hyf.github.io/calculator-refactor/)

- [x]  [DOM](link to branch for version 1)
- [ ]  [step 2](link to branch for version 2)
- [ ]  [step 3](link to branch for version 3)
- [x]  [Logic](link to branch for version 3)
- [x]  [Styles](link to branch for version 3)

### Exercises:
1. #### using-user-input
>- [ ] Turn on GitHub Pages
>- [ ] Complete 1-fill-in-the-blanks
>- [ ] Push your work regularly 
2. #### FreeCodeCamp JavaScript exercises 
>- [ ] Sign into FreeCodeCamp 
>- [ ] Turn on your Public Profile
>- [ ] Complete Basic JavaScript up through Golf Code
>- [ ] Copy-paste each and every exercise into JS Tutor to get the most out of your studying!
3. #### Continue studying the exercises from in class
>- [ ] study them live in the lesson plan 
>- [ ] clone this repository and try run the source files in Node.js
>- [ ] study the exercises in JS Tutor and practice them

**Comment by inglkruiz** [comment]
I saw you wrote the logic inside the file listener.js with a function `calc`. The calculator seems to work but your logic is not being tested against all the cases described in the file `logic.js`.
So... recommendation to make it work you need to move the logic you developed to the logic file inside doMath function, you can add it at the end.
From the function `doMath` return the value and in the calc function invoke/call the `doMath` function I mentioned.

The most important thing is to run your logic against the tests

**Comment by Rahela-HYF** [comment]
updatated
