### ISSUE TITLE
Shoaib: JS-week-1, Separation of Concerns (week-4)

### ISSUE THREAD

**Issue by shoaib-zaheer** [HackYourFutureBelgium/class-7#106]
#25 # Prep Work

- [x] **Andrew Mosh .**[`Video-1`](https://www.youtube.com/watch?v=upDLs1sn7g4), [`Video-2`](https://www.youtube.com/watch?v=W6NZfCO5SIk)
- [x] **Code School .**[`Video-1`](https://www.youtube.com/watch?v=nItSSTwBvSU), [`Video-2`](https://www.youtube.com/watch?v=OSWppEa2Zac)
- [x] **MDN: First Steps .**[`What is JavaScript`](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript)
- [x] **MDN: JS Basics .**[]()
- [x] **Javascript.info .**[](), [`ECMAScript`](https://en.wikipedia.org/wiki/ECMAScript#ES2019)
- [x] **script tag .** [`Link to READ`](https://javascript.info/hello-world)
- [x] **Code structure.**[`More INFO`](https://javascript.info/structure) [`Listeners event`](https://www.youtube.com/watch?v=QedZL8kXX6Y)

### Name of Project: 

- [`Repository`](https://github.com/shoaib-zaheer/calculator-refactor)
- [`live demo`](https://shoaib-zaheer.github.io/calculator-refactor/. )
- [x]  [DOM](https://github.com/shoaib-zaheer/calculator-refactor/commit/cc56ea925b79d5e682d9cec0e43e4152c84577e4)
- [x]  [Style](https://github.com/shoaib-zaheer/calculator-refactor/commit/4ce17fe730318539820244a6d21489ea99974f55)
- [x]  [Listener](https://github.com/shoaib-zaheer/calculator-refactor/commit/894f3fca35243758a2f7633a5fc212e4a38bd370)
- [x]  [Handler](https://github.com/shoaib-zaheer/calculator-refactor/commit/2cc95300094420197fa3c5939d00e0ef7aa6823c)
- [x]  [Logic](https://github.com/shoaib-zaheer/calculator-refactor/commit/fd6850fe3baab88e7082284ab8bef02ca0b66c73)

![Screenshot from 2020-02-11 00-53-10](https://user-images.githubusercontent.com/59531766/74201236-7798c880-4c69-11ea-8dcb-36efa5c15d70.png)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
