### ISSUE TITLE
ShtankoDaria: Week 2, separation of concepts

### ISSUE THREAD

**Issue by ShtankoDaria** [HackYourFutureBelgium/class-7#107]
### Prep Work
DevTools Debugger
- [x] [Step-by-Step intro](https://javascript.info/debugging-chrome)
- [x] [the debugger statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger)
- [x] [in Chrome/ium](https://developers.google.com/web/tools/chrome-devtools/javascript/)
- [x] [javascript.info](https://javascript.info/intro)

Isolating JavaScript
- [x] [Type Conversions: javascript.info/type-conversions](https://javascript.info/type-conversions)
- [x] [Operators & Comparisons: javascript.info/operators, javascript.info/comparison](https://javascript.info/operators)
- [ ] [Implicit Coercion](https://www.freecodecamp.org/news/js-type-coercion-explained-27ba3d9a2839/)
- [x] [Truthiness](https://github.com/janke-learning/truthiness)
- [x] [Loops](https://javascript.info/while-for)

Integrating JavaScript
- [x] [What are Events in JS?](https://www.youtube.com/watch?v=gx0oAgvXyE4)
- [ ] [Browser Events:](https://www.freecodecamp.org/news/js-type-coercion-explained-27ba3d9a2839/)
- [x] [UI Events](https://javascript.info/mouse-events-basics)

### Exercises:

Isolating JavaScript
- [x] [FreeCodeCamp JavaScript exercises:](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do...while-loops)
- [x] [Fork JS Exercise](https://github.com/CodeYourFuture/js-exercises/)

Integrating JavaScript
- [ ] [Fork listeners-and-handlers:](https://github.com/hackyourfuturebelgium/listeners-and-handlers)
- [ ] [handler-refactors](https://github.com/hackyourfuturebelgium/handler-refactors)
- [x] [Fork using-user-input](https://github.com/hackyourfuturebelgium/using-user-input)

soc-week-2-project
- [x] [repo](https://github.com/ShtankoDaria/soc-week-2-project)
- [x] [live](https://shtankodaria.github.io/soc-week-2-project/)
- [x] [devowel](https://github.com/ShtankoDaria/soc-week-2-project/tree/devowel)
- [x] [madlib](https://github.com/ShtankoDaria/soc-week-2-project/tree/madlib)
- [x] [repeater](https://github.com/ShtankoDaria/soc-week-2-project/tree/repeater)
- [x] [temp-converter](https://github.com/ShtankoDaria/soc-week-2-project/tree/temp-converter)
- [x] [pad-left](https://github.com/ShtankoDaria/soc-week-2-project/tree/padleft)

**Comment by ShtankoDaria** [comment]
@colevandersWands  @inglkruiz Blocked with temp-converter, it returns undefined value... (doesn't do calculations and returns the entered input with text 'is not surported)
https://github.com/ShtankoDaria/soc-week-2-project/blob/repeater/challenges/temp-converter.js

Also for repeater exercise, didn't manage to display on different lines just in one https://github.com/ShtankoDaria/soc-week-2-project/blob/temp-converter/challenges/repeater.js

Thanks

**Comment by colevandersWands** [comment]
@ShtankoDaria sorry for getting back to you a bit late, were you able to figure it out?

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
