### ISSUE TITLE
Nick: week 1, separation-of-concerns, isolate and integrate, progress

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#108]
### Progress:
I have watched the videos and other stuff that was in lesson plan slides, but wasn't observed in sundays lecture, plus ive done some simple exercises at pythontutor.
Well, i've almost finished the project (at least i thought i have). 

### Issues:
So, the main issue is, that i dived to quickly (again) into the project, as i see now, this topic needs more time, to be understood. 
 
### Next Steps:
So i am gonna watch more tutorials about js, and read more articles. Then gonna rewatch my **logic** in the project, and for the rest of time practise the code.

### Tip(s) of the week:
Dont dive, if u dont know how deep it is.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
