### ISSUE TITLE
Nour: Week 1, Sepraation Of Concerns

### ISSUE THREAD

**Issue by nouralkurd** [HackYourFutureBelgium/class-7#109]
### Prep Work

- [ ] one prep topic
- [x] the next prep topic
- [ ] ...

### Name of Project:

- [x] - [repository](github.com/user-name/repo-name)

- [x] - [live demo](http://127.0.0.1:5500/index.html)

**branches**
- [x]  [css](https://github.com/nouralkurd/calculator-refactor/commit/d94abed9f459eae272df0bc03902dab59f159cf2)
- [x]  [main body](https://github.com/nouralkurd/calculator-refactor/commit/56961b4f3611d09705587de3499d48e8d8a00b5a)
- [x]  [main logic](https://github.com/nouralkurd/calculator-refactor/commit/91e117cdc4fc491cdeabc47710db2c8e035f44d1)
- [x] [lisener](https://github.com/nouralkurd/calculator-refactor/commit/7eb0d8b3c492e7247107f483832329f9f2541a92) 
- [x] [handler](https://github.com/nouralkurd/calculator-refactor/commit/f9911ff2441fcf775ca11b904f2a26dd060cce58) 
### Exercises:

- [ ] exercise name: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
- [ ] exercise name: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
- [ ] ...

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
