### ISSUE TITLE
Rahel: Week 2, Separation-Of-Concerns 

### ISSUE THREAD

**Issue by Rahela-HYF** [HackYourFutureBelgium/class-7#111]
### Prep Work
###Step Through
#### DevTools Debugger
>- [x] Step-by-Step intro
>- [x] the debugger statement
>- [x] in Chrome/ium
>- [x] in FireFox

#### Isolating JavaScript
>- [x] Type Conversions: javascript.info/type-conversions
>- [x] Operators & Comparisons: javascript.info/operators, javascript.info/comparison
>- [x] Implicit Coercion: fcc/news/js-type-coercion
>- [x] Truthiness: janke-learning/truthiness
>- [x] Loops: javascript.info/while-for and complete the tasks

#### Integrating JavaScript
>- [x] What are Events in JS?
>- [x] Browser Events: javascript.info/introduction-browser-events
>- [x] UI Events: javascript.info/mouse-events-basics

### Project:SOC_Week2_Project
[repo](https://github.com/Rahela-HYF/soc-week-2-project)
[live](https://rahela-hyf.github.io/soc-week-2-project/)
>- [x] Devowel
>- [x] Madlib
>- [x] Pad_left
>- [x] repeater
>- [x] Temperature-Converter

### Exercises:
1. #### Fork listeners-and-handlers & handler-refactors
>- [x] Turn on GitHub Pages
>- [x] Push your work regularly
2. #### using-user-input
>- [ ] Turn on GitHub Pages
>- [ ] Complete 2-fix-the-bugs [ ]()
>- [ ] Push your work regularly 
3. #### FreeCodeCamp JavaScript exercises 
>- [ ] Sign into FreeCodeCamp 
>- [ ] Turn on your Public Profile
>- [ ] Complete Basic JavaScript up through  Iterate with JS do ... while loops
>- [ ] Copy-paste each and every exercise into JS Tutor to get the most out of your studying!
4. #### Continue studying the exercises from in class
>- [ ] study them live in the lesson plan 
>- [ ] example projects to study in example-projects.
>- [ ] clone this repository and try run the JS exercise source files in Node.js. Either way, study the exercises in JS Tutor and practice them

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
