### ISSUE TITLE
Ekaterina: Week 2, Separation of concerns

### ISSUE THREAD

**Issue by ekaterinaasf** [HackYourFutureBelgium/class-7#112]
### DevTools Debugger
- [x] [Step-by-Step intro](https://javascript.info/debugging-chrome)
- [x] [the debugger statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger)
- [x] [in Chrome/ium](https://developers.google.com/web/tools/chrome-devtools/javascript/)
- [ ] [javascript.info](https://javascript.info/intro)

### Isolating JavaScript
- [x] [Type Conversions: javascript.info/type-conversions](https://javascript.info/type-conversions)
- [x] [Operators & Comparisons: javascript.info/operators, javascript.info/comparison](https://javascript.info/operators)
- [ ] [Implicit Coercion](https://www.freecodecamp.org/news/js-type-coercion-explained-27ba3d9a2839/)
- [ ] [Truthiness](https://github.com/janke-learning/truthiness)
- [x] [Loops](https://javascript.info/while-for)

### Integrating JavaScript
- [x] [What are Events in JS?](https://www.youtube.com/watch?v=gx0oAgvXyE4)
- [ ] [Browser Events:](https://www.freecodecamp.org/news/js-type-coercion-explained-27ba3d9a2839/)
- [ ] [UI Events](https://javascript.info/mouse-events-basics)

### Isolating JavaScript:

- [x] FreeCodeCamp JavaScript exercises up through Iterate with JS do ... while loops
- [x] [JS Exercises](https://github.com/ekaterinaasf/js-exercises) in the folders called week-1 and week-1-practice

### Integrating JavaScript:

- [x] [listeners-and-handlers](https://github.com/ekaterinaasf/listeners-and-handlers)
- [x] [handler-refactors](https://github.com/ekaterinaasf/handler-refactors)
- [x] [using-user-input-2](https://github.com/ekaterinaasf/using-user-input/tree/master/2-fix-the-bugs) complete 2-fix-the-bugs
- [x] [using-user-input-3](https://github.com/ekaterinaasf/using-user-input/tree/master/3-develop-from-specifications) complete 3-develop-from-specs

### Project:

- [soc-week-2-project](https://github.com/ekaterinaasf/soc-week-2-project)
- [x]  [README](https://github.com/ekaterinaasf/soc-week-2-project/blob/master/README.md)
- [x]  [devowel](https://github.com/ekaterinaasf/soc-week-2-project/tree/devowel)
- [x]  [madlib](https://github.com/ekaterinaasf/soc-week-2-project/tree/madlib)
- [x]  [repeater](https://github.com/ekaterinaasf/soc-week-2-project/tree/repeater)
- [x]  [temp-converter](https://github.com/ekaterinaasf/soc-week-2-project/tree/temp-converter)
- [x]  [pad-left](https://github.com/ekaterinaasf/soc-week-2-project/tree/pad-left)

> [Follow this link](https://github.com/HackYourFutureBelgium/separation-of-concerns/tree/master/week-2#assignments)  to look at the homework for week 5.

**Comment by ekaterinaasf** [comment]
There are few questions for this https://github.com/ekaterinaasf/listeners-and-handlers
In exe-1 and exe-2 READMEs

**Comment by ekaterinaasf** [comment]
I'm stuck with https://github.com/ekaterinaasf/using-user-input/tree/master/2-fix-the-bugs/math-quiz
Cannot understand why result doesn't display. When I use browser's console and gave it a value, it's displayed correctly/

**Comment by colevandersWands** [comment]
@ekaterinaasf, it's a small mistake with capitalization, you wrote:
* `document.getElementById('user-action').addEventListener('mouseOver', showResult);`
it should be: 
* `document.getElementById('user-action').addEventListener('mouseover', showResult);`
no errors are thrown if the event type is spelled wrong, it just won't work

**Comment by ekaterinaasf** [comment]
Oh, Thank you very much, Evan. Now it works.

**Comment by ekaterinaasf** [comment]
Finished user-input and listener&handler exercises. There are some comments in commits. Could you, please, check if it is ok.

**Comment by ekaterinaasf** [comment]
I'm trying to resolve the project, made the first function, but second one - madlib doesn't work correctly and I cannot understand why. Рushed it here https://github.com/ekaterinaasf/soc-week-2-project/tree/madlib

**Comment by colevandersWands** [comment]
@ekaterinaasf.  can you turn on github pages for this week's project?  
and for the using-user-input exercises could you ask your questions as issues?  Commits aren't designed for conversations, just single message

**Comment by ekaterinaasf** [comment]
Turned.

Actually, they are not so necessary, but for any case. 3-develop-from-specs:
Google-search - I used string with URL, but not sure, but maybe we should use google API?

Slidulator - It seems there is an error in README - redundant first <option>. It doesn't display because of errors in mark-up, but it's visible when opened in VS.

**Comment by colevandersWands** [comment]
The url sting works and is the simplest. that's what is used in the duckduck example to study as well

For the madlibs, there's two things happening. 
* you forgot to declare the `stroka` variable using `let` or `const`, which actually declares it as a global variable (strange JS hoisting behavior)
* you misspelled the variable [right here](https://github.com/ekaterinaasf/soc-week-2-project/blob/madlib/challenges/madlib.js#L)
these two mistakes together mean that your function continues to return  `"the smooth steel ...` for the last 3 test cases.  See if you can't find this using the debugger

> i've fixed the README, thanks for the heads-up

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
