### ISSUE TITLE
Nick: Week 2, Separation of concerns, Step through

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#113]
### Exercises

- [x] [Freecodecamp](https://www.freecodecamp.org/mykola_marenich)
- [x] JS Exercises
[repo](https://github.com/NickMarinade/js-exercises) and [live](https://nickmarinade.github.io/js-exercises/)
- [x] Listeners-and-handlers
[repo](https://github.com/NickMarinade/listeners-and-handlers) and [live](https://nickmarinade.github.io/listeners-and-handlers/)
- [ ] Handler-refactors
[repo]() and [live]()
- [ ] Using-user-input
[repo]() and [live]()

### soc-week-2-project
[repo](https://github.com/NickMarinade/soc-week-2-project) and [live](https://nickmarinade.github.io/soc-week-2-project)
[devowel branch](https://github.com/NickMarinade/soc-week-2-project/tree/devowel)
[madlib branch](https://github.com/NickMarinade/soc-week-2-project/tree/madlib)
[repeater branch](https://github.com/NickMarinade/soc-week-2-project/tree/repeater)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
