### ISSUE TITLE
Shoaib: JS-week-2, Separation of Concerns (JS) week5

### ISSUE THREAD

**Issue by shoaib-zaheer** [HackYourFutureBelgium/class-7#114]
#### DevTools Debugger

- [x] Step-by-Step intro
- [x] The debugger statement
- [ ] In Chrome/ium
- [ ] In FireFox

#### Isolating JavaScript

- [ ] Type Conversions: javascript.info/type-conversions
- [ ] Operators & Comparisons: javascript.info/operators, javascript.info/comparison
- [ ] Implicit Coercion: fcc/news/js-type-coercion
- [ ] Truthiness: janke-learning/truthiness
- [ ] Loops: javascript.info/while-for and complete the tasks

#### Integrating JavaScript

- [x] What are Events in JS?
- [x] Browser Events: javascript.info/introduction-browser-events
- [x] UI Events: javascript.info/mouse-events-basics

#### Isolating JavaScript

- [x] Continue the FreeCodeCamp JavaScript exercises [`Picture`](#FreeCodeCamp)
- [x] Fork JS Exercises [`week-1`](https://github.com/shoaib-zaheer/js-exercises/tree/master/week-1), [`week-1-practice`](https://github.com/shoaib-zaheer/js-exercises/tree/master/week-1-practise/level-1)

#### Integrating JavaScript

- [x] Fork listeners-and-handlers
- [ ] handler-refactors
- [x] Fork using-user-input

##### FreeCodeCamp 
![Screenshot from 2020-02-14 21-40-22](https://user-images.githubusercontent.com/59531766/74566122-0875e980-4f73-11ea-81b5-e37ce885e85e.png)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
