### ISSUE TITLE
Oscar: Week 2, Separation of concerns

### ISSUE THREAD

**Issue by oscarpete** [HackYourFutureBelgium/class-7#115]
### Exercises

- [ ] [Freecodecamp](https://www.freecodecamp.org/oscarpete)
- [ ] JS Exercises
- [ ] Listeners-and-handlers
[repo]() and [live]()
- [ ] Handler-refactors
[repo]() and [live]()
- [ ] Using-user-input
[repo]() and [live]()

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
