### ISSUE TITLE
Elisa: Week 2, Separation of Concerns

### ISSUE THREAD

**Issue by Elisa0045** [HackYourFutureBelgium/class-7#118]
### Prep Work
DevTools Debugger
- [x] [Step-by-Step intro](https://javascript.info/debugging-chrome)
- [x] [the debugger statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger)
- [x] [in Chrome/ium](https://developers.google.com/web/tools/chrome-devtools/javascript/)
- [x] [javascript.info](https://javascript.info/intro)

Isolating JavaScript
- [x] [Type Conversions: javascript.info/type-conversions](https://javascript.info/type-conversions)
- [x] [Operators & Comparisons: javascript.info/operators, javascript.info/comparison](https://javascript.info/operators)
- [x] [Implicit Coercion](https://www.freecodecamp.org/news/js-type-coercion-explained-27ba3d9a2839/)
- [x] [Truthiness](https://github.com/janke-learning/truthiness)
- [x] [Loops](https://javascript.info/while-for)

Integrating JavaScript
- [x] [What are Events in JS?](https://www.youtube.com/watch?v=gx0oAgvXyE4)
- [x] [Browser Events:](https://www.freecodecamp.org/news/js-type-coercion-explained-27ba3d9a2839/)
- [x] [UI Events](https://javascript.info/mouse-events-basics)

### Exercises:

Isolating JavaScript
- [x] [FreeCodeCamp JavaScript exercises:](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do...while-loops)
- [x] [Fork JS Exercise](https://github.com/CodeYourFuture/js-exercises/)

Integrating JavaScript
- [x] [Fork listeners-and-handlers:](https://github.com/hackyourfuturebelgium/listeners-and-handlers)
- [x] [handler-refactors](https://github.com/hackyourfuturebelgium/handler-refactors)
- [x] [Fork using-user-input](https://github.com/hackyourfuturebelgium/using-user-input)

soc-week-2-project
- [x] [repo]()
- [x] [live]()

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
