### ISSUE TITLE
Nick: week 2, separation-of-concerns, step through, progress

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#119]
### Progress:
Last days was studying js at [FreeCodeCamp](https://www.freecodecamp.org/mykola_marenich), few more exercises and im ready to go. Plus watched some tutorials to go deeper in some aspects.

### Issues:
Nothing serious, was a little confused about arrays manipulations, but its ok now.
Serious issues gonna be on thursday and friday (**watch section next steps**)
 
### Next Steps:
This week, i got a main part of free time on thursday and friday, so the plan is to push pedal to the metal, start and finish all the exercises, and it would be perfect score to deal with project to (otherwise for saturday) 
### Tip(s) of the week:
function tip (a, b ) {
if ( a === "freeCodeCamp" || b === "jsTutor" ) {
return = "love";
}
}

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
