### ISSUE TITLE
Feridun Akyol: Week 3, separation of Concerns

### ISSUE THREAD

**Issue by feridunAKYOL** [HackYourFutureBelgium/class-7#123]
#### Isolating JavaScript
>- [x] Objects: javascript.info/type-conversions
>- [x] Arrays: javascript.info/operators
>- [x] Iterating Objects & Arrays: javascript.info/while-for and complete the tasks
>- [x] Arrow Functions - same idea, different spelling: javascript.info/arrow-functions-basics

### Project: soc-week-3-project

- [repository](https://github.com/feridunAKYOL/soc-week-3-project)
- [live demo](https://feridunakyol.github.io/soc-week-3-project/)
- [x]  [choices](https://github.com/feridunAKYOL/soc-week-3-project/pull/1/files)
- [x]  [repeatCharacters](https://github.com/feridunAKYOL/soc-week-3-project/pull/2/files)
- [x]  [replaceSubstring](https://github.com/feridunAKYOL/soc-week-3-project/pull/3/files)
- [x]  [reverseWords](https://github.com/feridunAKYOL/soc-week-3-project/pull/4/files)
- [x]  [sortCharacters](https://github.com/feridunAKYOL/soc-week-3-project/pull/5/files)

### Exercises:
1. #### FreeCodeCamp JavaScript exercises 
>- [x] Sign into FreeCodeCamp 
>- [x] Turn on your Public Profile
>- [x] Complete Basic JavaScript
![](https://raw.githubusercontent.com/feridunAKYOL/feridunakyol.github.io/master/js%20basic%20completed.png)
>- [x] Complete the Debugging challenges from FreeCodeCamp
>- [ ] Complete Basic Data Structures

2. #### JS Exercises
>- [x] week-2 [REPO](https://github.com/feridunAKYOL/js-exercises/tree/master/week-2)
>- [x] week-2-practice [REPO](https://github.com/feridunAKYOL/js-exercises/tree/master/week-2-practise)
>- [x] week-3 [REPO](https://github.com/feridunAKYOL/js-exercises/tree/master/week-3)
>- [x] week-3-practice [REPO](https://github.com/feridunAKYOL/js-exercises/tree/master/week-3-practise)

3. #### Fork listeners-and-handlers 
>- [x] Turn on GitHub Pages
>- [x] Push your work regularly [REPO](https://github.com/feridunAKYOL/listeners-and-handlers) and [LIVE](https://feridunakyol.github.io/listeners-and-handlers/)
4. #### Fork handler-refactors
>- [x] Turn on GitHub Pages
>- [x] Push your work regularly

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
