### ISSUE TITLE
Nick: Week 3, Separation of concerns

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#125]
### Exercises

- [x] [Freecodecamp](https://www.freecodecamp.org/mykola_marenich)
- JS Exercises
- [x] Week2
- [ ] Week3
[repo](https://github.com/NickMarinade/js-exercises) and [live](https://nickmarinade.github.io/js-exercises/)
- [ ] Listeners-and-handlers
[repo](https://github.com/NickMarinade/listeners-and-handlers) and [live](https://nickmarinade.github.io/listeners-and-handlers/)
- [ ] Handler-refactors
[repo]() and [live]()

### soc-week-3-project
[repo](https://github.com/NickMarinade/soc-week-3-project) and [live](https://nickmarinade.github.io/soc-week-3-project/)
- [x] [choices branch](https://github.com/NickMarinade/soc-week-3-project/tree/choices)
- [x] [reverse branch](https://github.com/NickMarinade/soc-week-3-project/tree/reverse)
- [x] [repeatChar branch](https://github.com/NickMarinade/soc-week-3-project/tree/repeatChar)
- [x] [replace branch](https://github.com/NickMarinade/soc-week-3-project/tree/replace)
- [x] [sort branch](https://github.com/NickMarinade/soc-week-3-project/tree/sort)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
