### ISSUE TITLE
Ekaterina: Week 3, Separation of Concerns

### ISSUE THREAD

**Issue by ekaterinaasf** [HackYourFutureBelgium/class-7#126]
### Prep Work

- [x] Objects: [javascript.info/type-conversions](https://javascript.info/type-conversions)
- [x] Arrays: [javascript.info/operators](https://javascript.info/operators)
- [x] Iterating Objects & Arrays: [javascript.info/while-for](https://javascript.info/while-for) and complete the tasks
- [x] Arrow Functions - same idea, different spelling: [javascript.info/arrow-functions-basics](https://javascript.info/arrow-functions-basics)

### Project: soc-week-3-project

- [repository](https://github.com/ekaterinaasf/soc-week-3-project)
- [live demo](https://ekaterinaasf.github.io/soc-week-3-project/)
- [ ]  [replace-substrings](https://github.com/ekaterinaasf/soc-week-3-project/tree/replace)
- [x]  [choices](https://github.com/ekaterinaasf/soc-week-3-project/tree/choices)
- [x]  [sort-characters](https://github.com/ekaterinaasf/soc-week-3-project/tree/sort)
- [x]  [reverse-words](https://github.com/ekaterinaasf/soc-week-3-project/tree/reverse)
- [x]  [repeat-characters](https://github.com/ekaterinaasf/soc-week-3-project/tree/repeat)

#### Continue the FreeCodeCamp JavaScript exercises: 
- [x] Complete [Basic JavaScript](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/)
![Screenshot from 2020-02-19 11-59-02](https://user-images.githubusercontent.com/59531760/74828383-4d9d7100-530f-11ea-94e8-34a90fccfe52.png)
- [x] Complete the [Debugging challenges](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/debugging/) from FreeCodeCamp
![Screenshot from 2020-02-19 12-13-56](https://user-images.githubusercontent.com/59531760/74829461-6018aa00-5311-11ea-9522-2dd7e6ca6f2f.png)
- [x] Complete [Basic Data Structures](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/)
![Screenshot from 2020-02-20 11-26-20](https://user-images.githubusercontent.com/59531760/74925085-e3023900-53d3-11ea-9729-0d8823770b39.png)

#### JS exercises
- [x] [week-2](https://github.com/ekaterinaasf/js-exercises/tree/master/week-2)
- [x] [week-2-practice](https://github.com/ekaterinaasf/js-exercises/tree/master/week-2-practise)
- [x] [week-3](https://github.com/ekaterinaasf/js-exercises/tree/master/week-3)
- [x] [week-3-practice](https://github.com/ekaterinaasf/js-exercises/tree/master/week-3-practise)

> [Follow this link](https://github.com/HackYourFutureBelgium/separation-of-concerns/tree/master/week-3#project) to study homework issue for week 6.

**Comment by ekaterinaasf** [comment]
I cannot understand few exercises of js-exercises.
1. https://github.com/ekaterinaasf/js-exercises/blob/master/week-2-practise/level-3/4-slice.js
According to the Readme it should return:
  [1, 3, 3]
  [1, 2, 3]
  [Irina, Ashleigh, Mozafar]
  [Irina, Ashleigh, Rares]

While mine returns:
[ 1, 2, 3 ]
[ 1, 2, 3 ]
[ 'Irina', 'Ashleigh', 'Rares' ]
[ 'Irina', 'Ashleigh', 'Rares' ]

2. https://github.com/ekaterinaasf/js-exercises/blob/master/week-2-practise/level-3/5-indexOf.js
Expected:
  [1, 3, 3]
  [1, 2, 3]
  [Irina, Ashleigh, Mozafar]
  [Irina, Rares, Mozafar]

Mine result is:
[ 1, 2, 3 ]
[ 1, 2, 3 ]
[ 'Irina', 'Rares', 'Mozafar' ]
[ 'Irina', 'Rares', 'Mozafar' ]

**Comment by ekaterinaasf** [comment]
Also stuck with Project: string replacement project:
https://github.com/ekaterinaasf/soc-week-3-project/blob/replace/challenges/replace-substring.js

Tried few options: used string.replace, used REGEX, used slice in loop, but still cannot resolve

**Comment by colevandersWands** [comment]
@ekaterinaasf 
first question: look through the slides from last sunday, at the end there's some bonus exercises on "reference vs value".   take a look at these, you'll see it again this sunday.   studying your code in JS Tutor will also help to see what's going on.  You've come across something called "side effects"

second question: have you just googled "javascript substring" yet?

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
