### ISSUE TITLE
shoaib: Week 3,separation-of-concerns JS

### ISSUE THREAD

**Issue by shoaib-zaheer** [HackYourFutureBelgium/class-7#127]
### Prep Work

- [ ] Objects: [`ToRead`](https://javascript.info/type-conversions)
- [ ] Arrays: [`ToRead`](https://javascript.info/operators)
- [ ] Iterating Objects & Arrays: [`ToRead`](https://javascript.info/while-for)
- [ ] Arrow Functions: [`ToRead`](https://javascript.info/arrow-functions-basics)
   [`Node.js`](https://www.youtube.com/watch?v=DsH-fizHkcY)[`JavaScript-Debugger`](https://www.youtube.com/watch?v=DsH-fizHkcY)

### Name of Project:

- [repository](github.com/user-name/repo-name)
- [live demo](https://user-name.github.io/repo-name)
- [ ]  [step 1](link to branch for version 1)
- [ ]  [step 2](link to branch for version 2)
- [ ]  [step 3](link to branch for version 3)
- [ ]  ...

### Exercises:

- [ ] Complete Basic JavaScript: []()
- [x] Debugging challenges from FreeCodeCamp: []() 
- [ ] Basic Data Structures: []()...
- [ ] JS Exercises [`week-2`](), [`week-2-practice`](), [`week-3`](), [`week-3-practice`]()

![Screenshot from 2020-02-21 00-27-02](https://user-images.githubusercontent.com/59531766/74989676-6c038980-5441-11ea-8d1e-ab8410acbbc4.png)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
