### ISSUE TITLE
Hakim: Week 3, Separation-of-Concerns

### ISSUE THREAD

**Issue by Hkm9** [HackYourFutureBelgium/class-7#128]
- [x] Isolating JavaScript
- [x] Continue the FreeCodeCamp JavaScript exercises
- [x] Fork [JS-Exercises](https://github.com/Hkm9/js-exercises) and Solve [week-2](https://github.com/Hkm9/js-exercises/tree/master/week-2), [week-2-practice](https://github.com/Hkm9/js-exercises/tree/master/week-2-practise), [week-3](https://github.com/Hkm9/js-exercises/tree/master/week-3) and [week-3-practice](https://github.com/Hkm9/js-exercises/tree/master/week-3-practise)
- [x] Fork [listeners-and-handlers](https://github.com/Hkm9/listeners-and-handlers) and Push your work regularly
- [x] Fork [handler-refactors](https://github.com/Hkm9/handler-refactors) and Push your work regularly
- [x] [soc-week-3-project](https://github.com/Hkm9/soc-week-3-project)

**Comment by dfdeagle47** [comment]
Closing old issues.
