### ISSUE TITLE
DariaS: Working with code, Week 1

### ISSUE THREAD

**Issue by ShtankoDaria** [HackYourFutureBelgium/class-7#13]
- [x] (computer) Software Installations
  - [x] [Chromium](https://download-chromium.appspot.com/), [Firefox](https://www.mozilla.org/en-US/firefox/developer/) or [Brave](https://brave.com/download/): All great browsers with ES6, HTML5 & CSS3 support plus pre-installed, top-knotch developer tools.  Try each one to see what you like best!
  - [x] [Visual Studio Code](https://code.visualstudio.com/download): Like Microsoft Word, but for code ...  and _sooooo_ much better.  After installing VSC, be sure to install these plug-ins:
    - [x] [Markdown Preview Github Styling Custom](https://marketplace.visualstudio.com/items?itemName=dmodalek.markdown-preview-github-styles-custom)
    - [x] [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
    - [x] [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview)
  - [x] [GitKraken](https://www.gitkraken.com/download): A program that will help you master using git.
  - [x] (If you have windows) [Git For Windows](https://gitforwindows.org/): This will allow you to use the same terminal commands & tools as Linux or Mac computers.
- [x] (computer) Start an HYF Directory
- [x] [My bio on the class repo](https://github.com/hackyourfuturebelgium/class-7/blob/master/student-bios/ShtankoDaria.md)
- [x] [Hack My Future](https://github.com/ShtankoDaria/hack-my-future)
- [x] [Markdown Home Page](https://ShtankoDaria.github.io/) - my multi-page markdown home portfolio, live on github pages

**Comment by ShtankoDaria** [comment]
My previous issue I copied from the class 8 (now I have 2 or even 3 if count the one we created in class 8, sorry), thought that's why I couldn't create a project. However looks like it's the same problem with a new template. 
Also links for "My bio on the class repo",  "Hack My Future" and
"Markdown Home Page" are not working.

**Comment by colevandersWands** [comment]
* the first one doesn't work because you haven't sent a Pull Request yet
* the second doesn't work because you didn't replace `my-user-name` with your actual user name
* the third one doesn't work because there is no `https://` in front of the link.  That's a mistake in the template, my apologies

**Comment by ShtankoDaria** [comment]
For the markdown home page, I don't understand why I don't see my tables in a table format. I tried change it in VSC and push with GitKraken but no matter what I do I still don't see emojis and table in my page, though in read.me file it seems ok. :(

**Comment by NickMarinade** [comment]
U have a mistake in your issue, in link to your page, u should change few things like that
![Новый точечный рисунок](https://user-images.githubusercontent.com/59340748/72071480-2e60fc00-32ec-11ea-8de1-19609970439e.png)

**Comment by ShtankoDaria** [comment]
I changed the name already but it's not the case, my table and emojis still don't display. Unless I am missing smth else 
![image](https://user-images.githubusercontent.com/59530782/72072384-1ab69500-32ee-11ea-9ec4-64a4354c4b58.png)

**Comment by colevandersWands** [comment]
I'm not entirely sure what's happening either, you can play around with different syntax if you like.  For me it's enough to already check off the assignment, you'll have a chance to rewrite your portfolio in HTML/CSS soon.  The main goal of this assignment was to find your way around github and you've already achieved that.

**Comment by ShtankoDaria** [comment]
Ok, thanks a lot Evan @colevandersWands ! :)

**Comment by colevandersWands** [comment]
@ShtankoDaria.  There's one thing with your student-bio, it appears that you have written it directly in this repo and not added it with a PR.  I can tell this because there are no [closed pull requests](https://github.com/HackYourFutureBelgium/class-7/pulls?q=is%3Apr+is%3Aclosed) from you and [your fork of this repo](https://github.com/ShtankoDaria/class-7/tree/master/student-bios) does not have your portfolio.

You can find more detailed steps on how to complete this assignment in the README of the student-bios folder.  After this you're done!

**Comment by ShtankoDaria** [comment]
@colevandersWands I created a pull request but not sure if it's correct or not. Got lost in the branches and folders :(

**Comment by colevandersWands** [comment]
What you did is a branch merge (you'll learn more about this next week).  Branches are sort of like forks, but inside one repository.  Instead you need to do a pull request across accounts.

To do a pull request instead of a merge, you will need to click the button that says "compare across forks".  Then you can select `hackyourfuturebelgium/master` instead of `shtankodaria/master`.  Besides this little difference the process will be exactly the same.

**Comment by ShtankoDaria** [comment]
@colevandersWands another attempt :)

**Comment by colevandersWands** [comment]
🎈 You're all DONE!
