### ISSUE TITLE
Elisa: Week3, Separation of Concerns 

### ISSUE THREAD

**Issue by Elisa0045** [HackYourFutureBelgium/class-7#131]
### Isolating JavaScript

>- [x] [Objects](https://javascript.info/type-conversions)
>- [x] [Arrays](javascript.info/operators)
>- [x] [Iterating Objects & Arrays & complete the tasks](https://javascript.info/while-for)
>- [x] [Arrow Functions - same idea, different spelling](https://javascript.info/arrow-functions-basics)

### Exercises
>- [x] Turn on your FreeCodeCamp Public Profile
>- [x] Complete the Debugging challenges
>- [x] [Complete Basic JavaScript](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/)
>- [x] [Complete Basic Data Structures](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/)
### Fork JS Exercises
>- [ ] Solve the Exercises in the folders called week-2, week-2-practice, week-3, and week-3-practice.
### Integrating JavaScript
>- [x]  Fork listeners-and-handlers
        Push your work regularly, so you can ask questions with issues!
 >- [x]  Fork handler-refactors
        Push your work regularly, so you can ask questions with issues!

### Project: soc-week-3-project
- [x] [Repo](https://github.com/Elisa0045/soc-week-3-project)
- [x] [Live](https://elisa0045.github.io/soc-week-3-project/)

### Step by step: Branches.
* [x] [Choices](https://github.com/Elisa0045/soc-week-3-project/tree/choices)
* [x] [Repeat-characters)](https://github.com/Elisa0045/soc-week-3-project/tree/repeat-characters)
* [x] [Replace-substring](https://github.com/Elisa0045/soc-week-3-project/tree/replace-substring)
* [x] [Reverse-words](https://github.com/Elisa0045/soc-week-3-project/tree/reverse-words)
* [x] [Sort-characters](https://github.com/Elisa0045/soc-week-3-project/tree/sort-characters)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
