### ISSUE TITLE
Nick: week 3, separation-of-concerns, progress

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#132]
### Progress:
Till that moment done almost all **FreeCodeCamp** exercise (basic js, debugging), got few more with Basic Data Structures. Also finished some exercises from last week.

### Issues:
Gonna ask more on sunday about **Ternary  Operator** and replacing loops using **Recursion**. In general that topics are clear, but not to the end.
 
### Next Steps:
As past week, got more time on thursday and friday, so plan is to do some exercises on thursday, and this weeks project for friday. All what left for saturday.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
