### ISSUE TITLE
Nick: Week 1, State, progress

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#147]
### Progress:

Till this moment have done js exercises, watched some tutorials form [The Coding Train](https://www.youtube.com/user/shiffman/videos), almost done exercises on FreeCodeCamp. Also read some documentation about some new methods.

### Issues:

Stuck a lil bit on how to write shorter code, for example declare a function without the `function` keyword and other. But it seems to be ok now.

### Next Steps:

Today gonna finish FreeCodeCamp exercises, for thursday more practise with exercises, and project if i dont struggle to much on exercises =) Otherwise, project for friday, and more practice for the rest of the time these week.

**Comment by colevandersWands** [comment]
@NickMarinade, i'd say don't worry about writing shorter code yet.  Write the code that is easiest for you to understand, shorter isn't always better

I'd also recommend spending at least an hour or so on the project Thursday so it sits in your head overnight.  it's also good practice with the debugger

**Comment by NickMarinade** [comment]
That was in an exercises, on JS week3, and with that exercises i also understood that "shorter isn't always better", 'cause i've wrote a long code much faster then the short one (even if it sounds strange).
And thanks for a tip)

**Comment by colevandersWands** [comment]
doesn't sound strange at all.  the easiest code to write is the code you understand best.  a lot of places online talk about how readable on-line code is, but that's only after a lot of experience.

and even with a lot of experience, shorter code can be much harder to step through and debug than longer code with more variales
