### ISSUE TITLE
Oscar: Week 2, State

### ISSUE THREAD

**Issue by oscarpete** [HackYourFutureBelgium/class-7#156]
### Prep Work

- [ ] Traversy DOM Crash Course 
- [ ] JS Dom Tutorials: Accessing The DOM
- [ ] DOM Tree (js.info)
- [ ] Walking the DOM (js.info)
- [ ] getElement & querySelector (js.info)

### Project: `Numbery-and-Nany`

- [repository](https://github.com/oscarpete/numbery-and-nany)
- [live demo](https://user-name.github.io/repo-name)
- [ ]  [step 1](link to branch for version 1)
- [ ]  [step 2](link to branch for version 2)
- [ ]  [step 3](link to branch for version 3)

#### Isolating JavaScript
- [ ]  js-exercises-tdd - `I.pass-tests`: [repo](https://github.com/user-name/repo-name), [live]()
- [ ]  early-return: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
>> - [ ] 1-isolate
>> - [ ] **2-integrate**  [repo](https://github.com/user-name/repo-name), [live]()

##### JS DOM Tutorials:
- [ ] Tutorial 1: Accessing the DOM
- [ ] Tutorial 2: Manipulating the DOM

### Challenge Exercises
- [ ] (Isolate) Continue Basic Algorithm Scripting
- [ ] (Isolate) Fork javascript-exercises
- [ ] (Integrate) Fork javascript-you__dom-exercises
- [ ] (Integrate) Fork practice-and-learn-the-dom
- [ ] (Integrate) Fork using-user-input

**Comment by dfdeagle47** [comment]
Closing old issues.

I still invite you to try to do the "Numbery-and-Nany" project because I think it's interesting and I know you can solve it :).

Don't hesitate to mention me in the issue and re-open it if you need some help.
