### ISSUE TITLE
Nick: Week 2, State, progress

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#159]
### Progress:

Because ive missed last sunday, i checked lesson plan, done some exercises from there. Also watched **Traversy DOM Crash Course**. After that course was able to manage with **JS DOM Tutorials**. Right now working on **early-return** exercises, Gonna finish today.

### Issues:

So far so good. 

### Next Steps:

So next steps, **Js-exercises-tdd** planned to start today and finish it tomorrow, also for tomorrow to start a project and further gonna see how it goes, if i got issues, gonna make deeper research about theme, but hopefully will be able to finish it by friday deadline. Rest of the week practise code, and preparing for next sunday class.

**Comment by dfdeagle47** [comment]
Closing in favor of #150.
