### ISSUE TITLE
Yared: Week 2 State

### ISSUE THREAD

**Issue by yaredyilma** [HackYourFutureBelgium/class-7#162]
### Prep Work

DOM Manipulation

- [x] [Traversy DOM Crash Course](https://www.youtube.com/watch?v=0ik6X4DJKCc)
- [x] [JS Dom Tutorials: Accessing The DOM](https://dom-tutorials.appspot.com/static/index.html)

- [x] [DOM Tree (js.info)](https://javascript.info/dom-nodes)

- [x] [Walking the DOM (js.info)](https://javascript.info/dom-navigation)

- [x] [getElement & querySelector (js.info)](https://javascript.info/searching-elements-dom)

Sunday Lesson Plan

- [ ] [Sunday lesson plan](https://hackyourfuture.be/state/week-3/#/cover-slide)

Exercises

- [ ] [js-exercises-tdd](https://github.com/yaredyilma/js-exercises-tdd)

Integrating JavaScript

- [ ] [dom-components](https://github.com/yaredyilma/dom-components)

Challenge Exercises

- [ ] Basic Algorithm [Scripting](https://www.freecodecamp.org/learn/)
![Screenshot 2020-03-05 at 02 50 38](https://user-images.githubusercontent.com/58144351/75940065-47b99b00-5e8c-11ea-8f14-f487941c8663.png)

- [ ] [javascript-exercises](https://github.com/yaredyilma/javascript-exercises)

- [ ] what is TDD?, online TDD exercises (no NPM troubles [:)](https://duckduckgo.com/?q=what+is+tdd%3F&iax=videos&ia=videos)[
](http://janke-learning.org/tdd/)
- [ ] [javascript-you__dom-exercises](https://github.com/yaredyilma/javascript-toy__dom-exercises)

- [ ] [practice-and-learn-the-dom](https://github.com/yaredyilma/practice-javascript-and-learn-the-dom)

- [ ] [using-user-input](https://github.com/yaredyilma/using-user-input)

**Comment by dfdeagle47** [comment]
Closing old issues.
