### ISSUE TITLE
Feridun: working with code, Week 1

### ISSUE THREAD

**Issue by feridunAKYOL** [HackYourFutureBelgium/class-7#17]
- [x] (computer) Software Installations
  - [x] [Chromium](https://download-chromium.appspot.com/), [Firefox](https://www.mozilla.org/en-US/firefox/developer/) or [Brave](https://brave.com/download/): All great browsers with ES6, HTML5 & CSS3 support plus pre-installed, top-knotch developer tools.  Try each one to see what you like best!
  - [x] [Visual Studio Code](https://code.visualstudio.com/download): Like Microsoft Word, but for code ...  and _sooooo_ much better.  After installing VSC, be sure to install these plug-ins:
    - [x] [Markdown Preview Github Styling Custom](https://marketplace.visualstudio.com/items?itemName=dmodalek.markdown-preview-github-styles-custom)
    - [x] [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
    - [x] [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview)
  - [x] [GitKraken](https://www.gitkraken.com/download): A program that will help you master using git.
  - [x] (If you have windows) [Git For Windows](https://gitforwindows.org/): This will allow you to use the same terminal commands & tools as Linux or Mac computers.
- [x] (computer) Start an HYF Directory
- [x] [My bio on the class repo](https://github.com/HackYourFutureBelgium/class-7/blob/master/student-bios/feridunAKYOL.md)
- [x] [Hack My Future](https://github.com/feridunAKYOL/hack-my-future)
- [x] [Markdown Home Page](https://github.com/feridunAKYOL/feridun.github.io) - my multi-page markdown home portfolio, live on github pages

**Comment by feridunAKYOL** [comment]
![112459](https://user-images.githubusercontent.com/59169551/71850072-c041ec80-30d3-11ea-9885-5d82b5f533f1.jpg)

**Comment by feridunAKYOL** [comment]
I achieved to upload a photo but not a nice one

**Comment by colevandersWands** [comment]
* You still need to create a home page in a repository called `feridunAKYOL.github.io`, you can find more detailed instructions for this in the assignments README
* In your `hack-my-future` repository, can you add a project board?

**Comment by feridunAKYOL** [comment]
_I think that now I am done_  :smile:

**Comment by colevandersWands** [comment]
One last little thing on the home page project: can you rename the repository to `https://feridunakyol.github.io/`?  You'll know it's correct when https://https://feridunakyol.github.io is a working URL.

Neat idea, placing the "learnables" board on your account instead of the repository.  Hadn't thought of that before.  Let me know over the weeks as you use it if this seems like a better way to do it, if so I'll change the assignment for next time

**Comment by feridunAKYOL** [comment]
:unicorn: 
thank you...
I used my way about  "learnables". if it works, I notify you..
have a good night :v: :

**Comment by colevandersWands** [comment]
✌️
