### ISSUE TITLE
Feridun Akyol : Week 1, Encapsulation

### ISSUE THREAD

**Issue by feridunAKYOL** [HackYourFutureBelgium/class-7#175]
#### Object Methods: this
- [x] [What is Object Oriented Programming? (1)](https://www.youtube.com/watch?v=rlLuL3jYLvA)
- [x] [What is Object Oriented Programming? (2)](https://www.youtube.com/watch?v=CXnnw9rQH5I)
- [x] javascript.info

#### Isolating JavaScript
- [x]  functions-to-methods: [repo](https://github.com/feridunAKYOL/functions-to-methods/blob/master/challenges/REVIEW.md)
- [x]  numbery-organizer: [repo](https://github.com/feridunAKYOL/numbery-organizer), [LIVE](https://feridunakyol.github.io/numbery-organizer/)
-   getters-and-setters: [repo](https://github.com/feridunAKYOL/getters-and-setters)
 - [x] getters [REVIEW](https://github.com/feridunAKYOL/getters-and-setters/blob/master/getters/REVIEW.md)
 - [x] setters [REVIEW](https://github.com/feridunAKYOL/getters-and-setters/blob/master/setters/REVIEW.md)
### Integrating JavaScript
- [ ]  Complete 1 JavaScript 30 group challenge with our group.

### Challenge Exercises
- [ ] [FCC Functional Programming](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/)
- [ ] [ FCC Intermediate Algorithm Scripting](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/)
- [x] [javascript-exercises](https://github.com/TheOdinProject/javascript-exercises).---> [REPO](https://github.com/feridunAKYOL/javascript-exercises)
- [x] Keep learning about TDD: [what is TDD?](https://duckduckgo.com/?q=what+is+tdd%3F&iax=videos&ia=videos)

### Name of Project: practical-javascript

- [repository](https://github.com/feridunAKYOL/practical-javascript)
- [live demo](https://feridunakyol.github.io/practical-javascript/)
- [x]  [Version-1](https://github.com/feridunAKYOL/practical-javascript/pull/1/files)
- [x]  [Version-2](https://github.com/feridunAKYOL/practical-javascript/pull/2/files)
- [x]  [Version-3](https://github.com/feridunAKYOL/practical-javascript/pull/3/files)
- [x]  [Version-4](https://github.com/feridunAKYOL/practical-javascript/pull/4/files)
- [x]  [Version-5](https://github.com/feridunAKYOL/practical-javascript/pull/5/files)
- [x]  [Version-6](https://github.com/feridunAKYOL/practical-javascript/pull/6/files)
- [x]  [Version-7](https://github.com/feridunAKYOL/practical-javascript/pull/7/files)
- [x]  [Version-8](https://github.com/feridunAKYOL/practical-javascript/pull/8/files)
- [x]  [Version-9](https://github.com/feridunAKYOL/practical-javascript/pull/10/files)
- [x]  [Version-10](https://github.com/feridunAKYOL/practical-javascript/pull/11/files)
- [x]  [Version-11](https://github.com/feridunAKYOL/practical-javascript/pull/12/files)
- [x]  [Version-12/Refactoring](https://github.com/feridunAKYOL/practical-javascript/pull/13/files)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by helene-nextmoov** [comment]
You did really good on the challenges.
I appreciated the fact that you're methods and all your code are clean, it's nice to see !

pratical-javascript : 
i like your styling :) !
Everything works perfectly.
Just be carefull about debugging statements left in your code : 
![image](https://user-images.githubusercontent.com/61017002/77831275-7dba0a00-712e-11ea-8c76-401a5c6dd4d7.png)
(Actually there was just one, i'm being picky)
If you want to clean code before commiting it, click on the magnifying glass button on the left pannel of VS Code and you'll be able to make a search in the entire project
![image](https://user-images.githubusercontent.com/61017002/77831337-d25d8500-712e-11ea-9dab-c2ab222619db.png)

**Comment by helene-nextmoov** [comment]
Good work anyway 👍

**Comment by feridunAKYOL** [comment]
@helene-nextmoov  thank you for your revision :pray:
