### ISSUE TITLE
Elisa0045 Working with the code week #1

### ISSUE THREAD

**Issue by Elisa0045** [HackYourFutureBelgium/class-7#25]
**Software Installations**
  - [x] [Chromium](https://download-chromium.appspot.com/), [Firefox](https://www.mozilla.org/en-US/firefox/developer/) or [Brave](https://brave.com/download/): All great browsers with ES6, HTML5 & CSS3 support plus pre-installed, top-knotch developer tools.  Try each one to see what you like best!
  - [x] [Visual Studio Code](https://code.visualstudio.com/download): Like Microsoft Word, but for code ...  and _sooooo_ much better.  After installing VSC, be sure to install these plug-ins:
    - [x] [Markdown Preview Github Styling Custom](https://marketplace.visualstudio.com/items?itemName=dmodalek.markdown-preview-github-styles-custom)
    - [x] [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
    - [x] [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview)
  - [x] [GitKraken](https://www.gitkraken.com/download): A program that will help you master using git.
- [x] (computer) Start an HYF Directory
- [x] [My bio on the class repo](https://github.com/hackyourfuturebelgium/class-7/blob/master/student-bios/Elisa0045.md)
- [x] [Hack My Future](https://github.com/Elisa0045/hack-my-future)
- [x] [Markdown Home Page](https://Elisa0045.github.io) - my multi-page markdown home portfolio, live on github pages

**Comment by colevandersWands** [comment]
@Elisa0045  One last touch.  You'll need to change your home page repository to `Elisa0045.githu.io`, then your'e good to go!

**Comment by Elisa0045** [comment]
Thank you for the advise!
its already done!

**Comment by colevandersWands** [comment]
Have you turned on GitHub pages?  This link is still dead: https://elisa0045.github.io/
 ( it can take a few minutes to work if you just turned it on )

**Comment by Elisa0045** [comment]
> Have you turned on GitHub pages? This link is still dead: https://elisa0045.github.io/
> ( it can take a few minutes to work if you just turned it on )

you can check now!

**Comment by colevandersWands** [comment]
I have checked, and it is live!
