### ISSUE TITLE
Nick: Week 1, Databases

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#253]
## Prep. Work:

- [x] [SQL Murder Mystery](https://mystery.knightlab.com/)
- [x] [SQLite Node.js Guide](https://www.sqlitetutorial.net/sqlite-nodejs/)
- [x] [Porting to a SQLite databasey](https://www.youtube.com/watch?v=2PCaD0Y4MP4&list=PLzV58Zm8FuBIWu1zvGRUfn0Xh6HXRg9cG&index=7)

## Exercises:

- [x] [CLI Query Scripts](https://github.com/NickMarinade/databases/commit/4405d816570b61afd0213c5ec97f575caaea08e9)

### [restful-chinook](https://github.com/NickMarinade/restful-chinook/commits/master)
- [x] [live on heroku](https://restful-nickhook.herokuapp.com)
- [x] Backend

**Comment by NickMarinade** [comment]
Backend is done, ill try to finish **front** and **deploy** project during friday and saturday.

**Comment by samicey** [comment]
Great Work @NickMarinade  . Your project is working fine.

**Comment by NickMarinade** [comment]
Thanks for review)
