### ISSUE TITLE
Nick: Week 1, Frontend Frameworks, wednesday check in

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#267]
### Progress:
 - Entering react world, watched video from facebook conference, which was suggested by Olivie.
Also started a detailed course on react.

### Next Steps:
- Keep studying the course, + we gonna have a lil online meetup with our subgroup tomorrow( about past module, on hot to connect back and front end).

**Comment by colevandersWands** [comment]
@NickMarinade , try taking a look through [this repo](https://github.com/HackYourFutureBelgium/organized-for-deployment/).  It's the start code we used for the last class' final project.  you can get an idea of how React and the backend can fit together in one project

**Comment by NickMarinade** [comment]
Thanks @colevandersWands , that would help a lot, ill definitely study this repo.
