### ISSUE TITLE
Landry

### ISSUE THREAD

**Issue by uwlanx** [HackYourFutureBelgium/class-7#40]
**Here is Landry**

![thumbnail](https://user-images.githubusercontent.com/59532059/72173811-a60c5500-33d8-11ea-9860-5e0e21fd814d.jpeg)

**About me**

Hello,

My name is Landry but my friends use to call me Wazza.
I striving here just to become a junior Web developer, and` so here I am to hack my future with HYF.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
