### ISSUE TITLE
Nick: week 1 - incremental development

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#42]
- [x] [Project](https://github.com/NickMarinade/acme-web-design.git)
- [x] [live](https://nickmarinade.github.io/acme-web-design/)
- Exercises:
- [x] [FreeCodeCamp](https://www.freecodecamp.org/mykola_marenich)
![Новый точечный рисунок](https://user-images.githubusercontent.com/59340748/72541498-ec532f80-3882-11ea-959e-1e8bf40afdf5.jpg)
- [x] [HTML-CSS-Practice-Problems](https://github.com/NickMarinade/HTML-CSS-Practice-Problems)
- [x] [live HTML-CSS-Practice-Problems](https://nickmarinade.github.io//HTML-CSS-Practice-Problems/level-1/)
- [x] [css-exercise1](https://github.com/NickMarinade/css-exercises/tree/master/exercise-1)
- [x] [live css-exercise1](https://nickmarinade.github.io/css-exercises/exercise-1/)

**Comment by NickMarinade** [comment]
If i already done FreeCodeCamp's Applied Accessibility challenges, but year before, should i do it again?

**Comment by KevinTss** [comment]
What you can do is make it on a new repository to have the history on you github account. It will help you to practise git.
You can try to make branches et merge them to master branch. And why not ask someone to review

**Comment by NickMarinade** [comment]
Stuck a lil bit in HTML-CSS-Practice-Problems.
So, ive done step 1, and when ive started step 2, i got the same html file, but other css file "step-2.css".
And when i work with this css file, nothing changes in html( and that logical, there are nothing that uses classes from "step-2.css"). So, what am i losing?
![Новый точечный рисунок](https://user-images.githubusercontent.com/59340748/72552706-c3896500-3897-11ea-993f-c4fcef61dd39.jpg)

**Comment by KevinTss** [comment]
Hmmm are you suppose to mix all step css files?
Can you provide the link of your repo where you push that? Then we can look at the code and help better

**Comment by NickMarinade** [comment]
https://github.com/NickMarinade/HTML-CSS-Practice-Problems

**Comment by NickMarinade** [comment]
Step 1
Open **level-1/index.html** && level-1/step-1.css && level-1/step-1.jpg.
...
Step 2
Open **level-1/index.html** && level-1/step-2.css && level-1/step-2.jpg.
...

**Comment by KevinTss** [comment]
Ok I just checked, what's exactly the problem that you have? 
Because all css are correctly applied
What is the result that you expect?

**Comment by NickMarinade** [comment]
Ok, solved, i thought that nothing changes on html page, but as i worked further with height and width in step-2.css, it react. Just have to wait a little, sorry)

**Comment by colevandersWands** [comment]
@NickMarinade.  can you push the rest of your branches for this project?  On github there is only master & header (https://github.com/NickMarinade/acme-web-design/branches).  Your development strategy is great!  Now we want to see the steps on github as well

**Comment by NickMarinade** [comment]
Oh, yes, my fault, sorry. Just pushed all the branches from my local.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
