### ISSUE TITLE
Mai: week 1 - incremental development

### ISSUE THREAD

**Issue by mai-mr-mahmoud** [HackYourFutureBelgium/class-7#44]
### Prep Work

Git, GitHub & GitKraken
- [x] git & github for poets - watch through 1.4
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
![image](https://user-images.githubusercontent.com/58188273/72227653-86735900-359f-11ea-8313-e4c08f78b168.png)

- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits

User Stories
- [x] Agile Development by Cartoon
- [x] Splitting User Stories
- [x] The "what" not the "how"

Relative vs. Absolute Paths
- [x] Relative vs. Absolute Paths

Internet?
- [x] How the Internet Works in 5 Minutes
- [x] How do Web Browsers Work?

Code Review
- [x] Take a look through this page from Study

### Code-Along:

- [repository](https://github.com/mai-mr-mahmoud/acme-web-design)
- [live demo](https://mai-mr-mahmoud.github.io/acme-web-design)
- [x] [Home Layout](https://github.com/mai-mr-mahmoud/acme-web-design/tree/home-layout)
- [x] [Home Showcase](https://github.com/mai-mr-mahmoud/acme-web-design/tree/home-showcase)
- [x] [Home Boxes](https://github.com/mai-mr-mahmoud/acme-web-design/tree/home-boxes)
- [x] [About Layout](https://github.com/mai-mr-mahmoud/acme-web-design/tree/about-layout)
- [x] [About Main](https://github.com/mai-mr-mahmoud/acme-web-design/tree/about-main)
- [x] [About Sidebar](https://github.com/mai-mr-mahmoud/acme-web-design/tree/about-sidebar)
- [x] [Services Layout](https://github.com/mai-mr-mahmoud/acme-web-design/tree/services-layout)
- [x] [Services Service List](https://github.com/mai-mr-mahmoud/acme-web-design/tree/services-service-list)
- [x] [Services Quotation](https://github.com/mai-mr-mahmoud/acme-web-design/tree/services-quotation)

### Exercises:

- [x] Sign in to FreeCodeCamp using your GitHub account:
       Complete all 22 of FreeCodeCamp's Applied Accessibility challenges.
       Turn on your public portfolio so we can give feedback on your code
https://www.freecodecamp.org/fccbe19b110-771d-4117-bec4-730081c87f1a
![image](https://user-images.githubusercontent.com/58188273/72572561-3825c900-38c3-11ea-8a66-d97f4662f902.png)

- [x] Fork and Clone HTML-CSS-Practice-Problems:
      Turn on GitHub Pages
       Complete the exercises in ./level-1
https://github.com/mai-mr-mahmoud/HTML-CSS-Practice-Problems
https://mai-mr-mahmoud.github.io//HTML-CSS-Practice-Problems/level-1/

- [ ] Fork and Clone css-exercises
       Turn on GitHub Pages
       Complete exercise-1 and exercise-2

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
