### ISSUE TITLE
feridunAkyol: Week 1, Incremental Development

### ISSUE THREAD

**Issue by feridunAKYOL** [HackYourFutureBelgium/class-7#45]
### Prep Work

Git, GitHub & GitKraken
- [x] git & github for poets - watch through 1.4
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
![](https://raw.githubusercontent.com/feridunAKYOL/feridunakyol.github.io/master/Screenshot%20from%202020-01-17%2023-26-26.png)

- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits

User Stories
- [x] Agile Development by Cartoon
- [x] Splitting User Stories
- [x] The "what" not the "how"

Relative vs. Absolute Paths
- [x] Relative vs. Absolute Paths

Internet?
- [x] How the Internet Works in 5 Minutes
- [x] How do Web Browsers Work?

Code Review
- [x] Take a look through this page from Study

### Acme-Web-Design:

- [repository](https://github.com/feridunAKYOL/acme-web-design)
- [live demo](https://feridunakyol.github.io/acme-web-design/)
- [x]  [step-1 start point](https://github.com/feridunAKYOL/acme-web-design/pull/1/files#diff-eacf331f0ffc35d4b482f1d15a887d3b)
- [x]  [step-2 Main Parts of HTML ](https://github.com/feridunAKYOL/acme-web-design/pull/2/files#diff-eacf331f0ffc35d4b482f1d15a887d3b)
- [x]  [step-3 Header Menu](https://github.com/feridunAKYOL/acme-web-design/pull/3/files)
- [x]  [step-4 Showcase Area](https://github.com/feridunAKYOL/acme-web-design/pull/4/files)
- [x]  [Step-5 Mail Subscribe](https://github.com/feridunAKYOL/acme-web-design/pull/5/files)
- [x]  [Step-6 Boxes](https://github.com/feridunAKYOL/acme-web-design/pull/6/files)
- [x]  [Step-7 footer](https://github.com/feridunAKYOL/acme-web-design/pull/7/files)
- [x]  [Step-8 About Page](https://github.com/feridunAKYOL/acme-web-design/pull/8/files)
- [x]  [Step-9 Services](https://github.com/feridunAKYOL/acme-web-design/pull/9/files)
- [x]  [Step-10 responsive](https://github.com/feridunAKYOL/acme-web-design/pull/10/files)

### Exercises:

- [x] Free Code Camp : [Applied accebility-22 lessons](https://www.freecodecamp.org/feridunakyol)
![](https://raw.githubusercontent.com/feridunAKYOL/feridunakyol.github.io/master/freecodecamp.png)

- [x] HTML-CSS-Practice-Problems-Level 1: [repo](https://github.com/feridunAKYOL/HTML-CSS-Practice-Problems), [live](https://feridunakyol.github.io/HTML-CSS-Practice-Problems/level-1/)
- [x] css-exercises/ [exercises-1](https://github.com/feridunAKYOL/css-exercises/pull/1/files) [live](https://feridunakyol.github.io/css-exercises/exercise-1/)
- [x] css-exercises/ [exercises-2](https://github.com/feridunAKYOL/css-exercises/pull/2/files) [live](https://feridunakyol.github.io/css-exercises/exercise-2/)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
