### ISSUE TITLE
Oscar: Week 1, Incremental development

### ISSUE THREAD

**Issue by oscarpete** [HackYourFutureBelgium/class-7#46]
### Prep Work

Git, GitHub & GitKraken
- [x] git & github for poets - watch through 1.4
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
![Captura5555](https://user-images.githubusercontent.com/59342211/72445596-420bd700-37b2-11ea-9ec4-3eb9556d358b.JPG)

- [x] Familiarize yourself with GitKraken
- [x] Study this [example project] (https://github.com/oscarpete/built-with-branches)
- [x] Understand how to use Atomic Commits

User Stories
- [x] Agile Development by Cartoon
- [x] Splitting User Stories
- [x] The "what" not the "how"

Relative vs. Absolute Paths
- [x] Relative vs. Absolute Paths

Internet?
- [x] How the Internet Works in 5 Minutes
- [x] How do Web Browsers Work?

Code Review
- [x] Take a look through this page from Study

### Code-Along:

- [repository](https://github.com/oscarpete/acme-web-design)
- [live demo](https://oscarpete.github.io/acme-web-design/)
- [x]  [step 1](https://github.com/oscarpete/acme-web-design/tree/NavigationBar)
- [x]  [step 2](https://github.com/oscarpete/acme-web-design/tree/showcase)
- [x]  [step 3](https://github.com/oscarpete/acme-web-design/tree/newsletter-and-boxes)
- [x]  [step 3](https://github.com/oscarpete/acme-web-design/tree/footer1)

### Exercises:

- [x] Sign in to FreeCodeCamp using your GitHub account: [repo](https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/)
    - [x]  [step 1] Complete all 22 of FreeCodeCamp's Applied Accessibility challenges.
    - [x]  [step 2] Turn on your public portfolio(https://www.freecodecamp.org/oscarpete) so we can give feedback on your code

- [x] Fork and Clone HTML-CSS-Practice-Problems: [repo](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
    - [x]  [step 1] Turn on GitHub Pages
    - [x]  [step 2] Complete the exercises in ./level-1

- [x] Fork and Clone css-exercises: [repo](https://github.com/dangodev/css-exercises)
    - [ ]  [step 1] Turn on GitHub Pages
    - [ ]  [step 2] Complete exercise-1 and exercise-2

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

*Copied from the great work of Mai @mai-mr-mahmoud

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
