### ISSUE TITLE
Daria Shtanko: week 1 - incremental development

### ISSUE THREAD

**Issue by ShtankoDaria** [HackYourFutureBelgium/class-7#47]
### Prep Work

- [x] git & github for poets - watch through 1.4 
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits

User Stories
-  [x] Agile Development by Cartoon
-  [x] Splitting User Stories
-  [x] The "what" not the "how"

Relative vs. Absolute Paths
Not super complicated, but a little tricky at first. And this will come up all the time forever.

-  [x] relative vs. absolute paths

Internet?
-  [x] How the Internet Works in 5 Minutes
-  [x] How do Web Browsers Work?

### Name of Project:

- [x] [repository](https://github.com/ShtankoDaria/acme-web-design)
- [x] [live demo](https://shtankodaria.github.io/acme-web-design/)
- [x]  [step 1: Create index.html file for Home Page](https://github.com/ShtankoDaria/acme-web-design/tree/Home-page)
- [x]  [step 2: Create Style.css file in the folder CSS to style the website](https://github.com/ShtankoDaria/acme-web-design/tree/Style-css)
- [x]  [step 3: Create About Page](https://github.com/ShtankoDaria/acme-web-design/tree/About-page)
- [x]  [step 4: Create Services Page](https://github.com/ShtankoDaria/acme-web-design/tree/Services)

### Exercises:

- [x] Applied Accessibility: [freecodecamp](https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/use-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements) 
![image](https://user-images.githubusercontent.com/59530782/72547287-a7cc9180-388c-11ea-8167-3f435680dff9.png)

- [x] HTML-CSS-Practice-Problems: [Level 1](https://github.com/ShtankoDaria/HTML-CSS-Practice-Problems/tree/master/level-1) 
- [x] css-exercises [exercise 1](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-1)
- [x] css-exercises [exercise 2](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-2)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
