### ISSUE TITLE
Ekaterina: Week 1, Incremental development

### ISSUE THREAD

**Issue by ekaterinaasf** [HackYourFutureBelgium/class-7#48]
### Prep Work

- [x] git & github for poets - watch through 1.4
- [x] LearnGitBranching & video tutorial - complete the first set of exercise
- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits

### User Stories

- [x] Agile Development by Cartoon
- [x] Splitting User Stories
- [x] The "what" not the "how"
- [x] Relative vs. Absolute Paths
- [x]  How the Internet Works in 5 Minutes
- [x] How do Web Browsers Work?

### Code Review

- [x] Take a look through this page from Study

### Project

- [x] Code-Along
- [x] Responsive Layout tutorial

### Exercises:

- [x] Sign in to FreeCodeCamp using your GitHub account: [repo](https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/)
    - [x]  [step 1] Complete all 22 of FreeCodeCamp's Applied Accessibility challenges.
    - [x]  [step 2] Turn on your public portfolio so we can give feedback on your code
![Screenshot from 2020-01-15 14-31-24](https://user-images.githubusercontent.com/59531760/72665848-a1fdba00-3a0c-11ea-8803-93b7c8bd1ed0.png)

- [x] Fork and Clone HTML-CSS-Practice-Problems: [repo](https://github.com/ekaterinaasf/HTML-CSS-Practice-Problems)
    - [x]  [step 1] Turn on GitHub Pages
    - [x]  [step 2] Complete the exercises in ./level-1

- [x] Fork and Clone css-exercises: [repo](https://github.com/ekaterinaasf/css-exercises)
    - [x]  [step 1] Turn on GitHub Pages
    - [x]  [step 2] Complete exercise-1 and exercise-2

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
