### ISSUE TITLE
Yared Yilma: week 1 - incremental development

### ISSUE THREAD

**Issue by yaredyilma** [HackYourFutureBelgium/class-7#49]
- [x] - [ ] git & github for poets - watch through 1.4

- [x] LearnGitBranching & video tutorial - complete the first set of exercises
- [x] Familiarise yourself with GitKraken
- [x] Study the example project
- [x] Understand how to use Atomic Commits

- [x] Agile Development by Cartoon

- [x] Splitting User Stories

- [x] The "what" not the "how"

- [x] relative vs. absolute paths

- [x] How the Internet Works in 5 Minutes

- [x] How do Web Browsers Work?

- [x] Take a look through this page from Study

- [x] Code-Along

- [x] Responsive Layout

- [x] Applied Accessibility 

- [x] HTML-CSS-Practice-Problems:

- [x] css-exercises

**Comment by yaredyilma** [comment]
Adding what's in progress.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
