### ISSUE TITLE
Elisa: week 1, Incremental Development 

### ISSUE THREAD

**Issue by Elisa0045** [HackYourFutureBelgium/class-7#50]
### Prep Work

- [x] git & github for poets - watch through 1.4
- [x] LearnGitBranching & video tutorial - complete the first set of exercise

![Screenshot 2020-01-15 at 00 12 21](https://user-images.githubusercontent.com/59478770/72395286-42b45700-3739-11ea-91cf-3be54d248d97.png)

![Screenshot 2020-01-15 at 01 48 32](https://user-images.githubusercontent.com/59478770/72395288-45af4780-3739-11ea-99e4-f32bb7602a9b.png)

- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits

### User Stories

- [x] Agile Development by Cartoon
- [x] Splitting User Stories
- [x] The "what" not the "how"
- [x] Relative vs. Absolute Paths
- [x]  How the Internet Works in 5 Minutes
- [x] How do Web Browsers Work?

### Code Review

- [x] Take a look through this page from Study

### Exercises:

- [ ] Sign in to FreeCodeCamp using your GitHub account: [repo](https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/)
    - [ ]  [step 1] Complete all 22 of FreeCodeCamp's Applied Accessibility challenges.
    - [ ]  [step 2] Turn on your public portfolio so we can give feedback on your code

- [ ] Fork and Clone HTML-CSS-Practice-Problems: [repo](https://github.com/DevMountain/HTML-CSS-Practice-Problems)
    - [ ]  [step 1] Turn on GitHub Pages
    - [ ]  [step 2] Complete the exercises in ./level-1

- [ ] Fork and Clone css-exercises: [repo](https://github.com/dangodev/css-exercises)
    - [ ]  [step 1] Turn on GitHub Pages
    - [ ]  [step 2] Complete exercise-1 and exercise-2

> [Follow this link](https://github.com/HackYourFutureBelgium/class-7/issues/59) to study a well-done homework issue.

### Project:
- [x]  Name of Project: acme-web-design 
* [Repository](https://github.com/Elisa0045/acme-web-design)
* [Live demo](https://elisa0045.github.io/acme-web-design/) 
- [x]  [Starting](https://github.com/Elisa0045/acme-web-design/tree/starting)
- [x]  [Making header](https://github.com/Elisa0045/acme-web-design/tree/making-header)
- [x] [Show case area](https://github.com/Elisa0045/acme-web-design/tree/show-case-area)
 - [x]  [Newsletter section](https://github.com/Elisa0045/acme-web-design/tree/newsletter-section)
- [x] [Service Area](https://github.com/Elisa0045/acme-web-design/tree/service-area)
- [x]  [Footer](https://github.com/Elisa0045/acme-web-design/tree/footer)
- [x] [Styling Home page](https://github.com/Elisa0045/acme-web-design/tree/styling-home-page)
 - [x]  [About page](https://github.com/Elisa0045/acme-web-design/tree/about-page)
- [x] [Services page](https://github.com/Elisa0045/acme-web-design/tree/services-page)
- [x]  [Media Querties](https://github.com/Elisa0045/acme-web-design/tree/media-queries)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
