### ISSUE TITLE
Boam1994: Week 1, incremental development

### ISSUE THREAD

**Issue by Boam1994** [HackYourFutureBelgium/class-7#51]
### Prep Work
Git, GitHub & GitKraken
- [x] git & github for poets-watch through 1-3
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
[image](https://user-images.githubusercontent.com/59532845/72912955-b27ba080-3d3c-11ea-8268-6c902955b948.png) 
- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits
### User Stories:
- [x] Agile Development by Cartoon
- [x] Splitting User Stories
- [x] The "what" not the "how"
### Relative vs. Absolute Paths
- [x] Relative vs. Absolute Paths
### Internet?
- [x] How the Internet Works in 5 Minutes
- [x] How do Web Browsers Work?
Code Review
- [x] Take a look through this page from Study
###Code-Along:

- [repository](https://github.com/boam1994/acme-web-design)
- [live demo](https://boam1994.github.io/acme-web-design/)
- [x]  [Home](https://boam1994.github.io/acme-web-design/index.html)
- [x]  [About](https://boam1994.github.io/acme-web-design/about.html)
- [x]  [Services](https://boam1994.github.io/acme-web-design/services.html)
- [ ]  ...

### Exercises:
- [ ]Complete all 22 of FreeCodeCamp's Applied Accessibility challenges.
[ Screenshot
![image](https://user-images.githubusercontent.com/59532845/72978616-15217a80-3dd7-11ea-81c5-45890ac32eae.png)
]
- [ ] exercise name: [repo](https://github.com/boam1994/acme-web-design), [live (if there is)]()
- [ ] exercise name: [repo](https://github.com/boam1994/acme-web-design), [live (if there is)]()
- [ ] ...

> [Follow this link](https://github.com/HackYourFutureBelgium/class-7/issues/51) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
