### ISSUE TITLE
Shoaib: Week 2, incremental development

### ISSUE THREAD

**Issue by shoaib-zaheer** [HackYourFutureBelgium/class-7#52]
### Prep Work

- [x] Reading the week2 Topics
- [x] Git Tutorial for Beginners: Command-Line Fundamentals [`LINK`](https://www.youtube.com/watch?v=dG0ke9vILQM)
- [x] creating TEST "REPO" for relation between (Master & Branch). [`REPO`](https://github.com/shoaib-zaheer/TEST) [`COMMITS`](https://github.com/shoaib-zaheer/TEST/commits/master)
- [x] Introduction to Scrum - 7 Minutes [`VIDEO`](https://www.youtube.com/watch?v=9TycLR0TqFA)
- [x] Familiarized with browser `WEB-Developer` & `DOM` 
> * Toggle Tools
> * Inspector 
> * Console
> * Debugger
> * Network
> * Style Editor
> * Performance
> * Memory
> * Storage
> * Accessibility
> * ETC

- [x] What is Responsive Web Design?

### Name of Project: Branching-page

- [App-theme](https://github.com/shoaib-zaheer/app-theme)
- [live demo](https://shoaib-zaheer.github.io/app-theme/)
- [Development-Strategy.md](https://github.com/shoaib-zaheer/app-theme/blob/master/Development-Strategy.md)
- [x]  [step/commit 1](https://github.com/shoaib-zaheer/app-theme/commit/cf291143121a5da13c4658f23e6a8931177c68cc)
- [x]  [step/commit 2](https://github.com/shoaib-zaheer/app-theme/commit/f32a243ebaeca80bc89716fd038e86bc61988232)
- [x]  [step/commit 3](https://github.com/shoaib-zaheer/app-theme/commit/3f6dd92c16b917d284d0d25929255a770d748198)
- [x]  [step/commit 4](https://github.com/shoaib-zaheer/app-theme/commit/6dc8a177098e335fa3b4237908f6c256f61ba68c)
- [x]  [step/commit 5](https://github.com/shoaib-zaheer/app-theme/commit/731f1c40f0a0f60fe8c4f299bf76cc6a7e740e37)
- [x]  [step/commit 6](https://github.com/shoaib-zaheer/app-theme/commit/051942e1b219b4a30fa4c54037082cfeb16199d4)
- [x]  [step/commit 7](https://github.com/shoaib-zaheer/app-theme/commit/ad111813f8a814c7c939a997d573c37f8ef8c17d)
- [x]  [step/commit 8](https://github.com/shoaib-zaheer/app-theme/commit/5e1f5b7156c3399df13a373c2dc63c24651600c7)
- [x]  [step/commit 9](https://github.com/shoaib-zaheer/app-theme/commit/79fd53811551d1e4f48bfa7b282e3bfd7c2e93de)
- [x]  [step/commit 10](https://github.com/shoaib-zaheer/app-theme/commit/4e01088c0a8aca0c837484786879fe72e580bd6c)
- [x]  [step/commit 11](https://github.com/shoaib-zaheer/app-theme/commit/bd53584bebb4819aa71a41ca2adbc075c07b3332)
- [x]  [step/commit 12](https://github.com/shoaib-zaheer/app-theme/commit/de632d822f6f30238d46d61a41249e12291ad452)
- [x]  [step/commit 13](https://github.com/shoaib-zaheer/app-theme/commit/397bb1ee0e53af9b51c5e70342c08cb92528f5c2)
- [x]  [step/commit 14](https://github.com/shoaib-zaheer/app-theme/commit/e758dc8b10cc9755fc3562bb5138fea81d69a9ef)
- [x]  [step/commit 15](https://github.com/shoaib-zaheer/app-theme/commit/fbe42da2182bfe1fdf6c3fcbf4d47e820cebe86a)
- [x]  [step/commit 16](https://github.com/shoaib-zaheer/app-theme/commit/5ac67c889e4d9a61cfa74d758f1655ce3bf27bf5)
- [x]  [step/commit 17](https://github.com/shoaib-zaheer/app-theme/commit/95bd20815d3e939fe5a00644884c3312ca727b2b)
- [x]  [step/commit 18](https://github.com/shoaib-zaheer/app-theme/commit/72406a3b5f21650a3ceb6ec7c9e27267441b9e05)
- [x]  [step/commit 19](https://github.com/shoaib-zaheer/app-theme/commit/0d2cab8b4ca01f68278aada1ec2f2deb8d85a7cc)
- [x]  [step/commit 20](https://github.com/shoaib-zaheer/app-theme/commit/a659449696326224ced3d277fff342554b7a5fe5)
- [x]  [step/commit 21](https://github.com/shoaib-zaheer/app-theme/commit/ced170fdea977772f0c4f3e20c7e551153862980)
- [x]  [step/commit 22](https://github.com/shoaib-zaheer/app-theme/commit/eba308b5b09ada7c8f656072c9c76bf996549465)
- [x]  [step/commit 23](https://github.com/shoaib-zaheer/app-theme/commit/04373f2efb44fd009fd29921d12200b99584318a)
- [x]  [step/commit 24](https://github.com/shoaib-zaheer/app-theme/commit/a0272356515e1fe0c42d9a7d833b2f9d96d97cfe)
- [x]  [step/commit 25](https://github.com/shoaib-zaheer/app-theme/commit/d3deb92cb1406aa1226678a8a9f9d11e9d900608)

### Exercises:

- [X] HTML-CSS-Practice-Problems : [repo Level-2, Step-2 ](https://github.com/shoaib-zaheer/HTML-CSS-Practice-Problems/tree/master/level-2)
- [x] CSS-EXERCISES: [Exercises-3](https://github.com/shoaib-zaheer/css-exercises/tree/master/exercise-3), [Exercises-4](https://github.com/shoaib-zaheer/css-exercises/tree/master/exercise-4), [Exercises-5](https://github.com/shoaib-zaheer/css-exercises/tree/master/exercise-5)

![Screenshot from 2020-01-22 02-04-07](https://user-images.githubusercontent.com/59531766/72857436-e6fc4780-3cbd-11ea-8ab4-6e949d770217.png)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
