### ISSUE TITLE
Hakim: week 1 - incremental development

### ISSUE THREAD

**Issue by Hkm9** [HackYourFutureBelgium/class-7#53]
- [x] git & github for poets
- [x] LearnGitBranching & video tutorial 
- [x] complete the first set of exercises
![Screenshot 2020-01-15 at 14 44 28](https://user-images.githubusercontent.com/55857486/72441342-cd816a00-37aa-11ea-8ea7-9dc653aa605a.png)
- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits
- [x] User Stories (3 vids)
- [x] Relative vs. Absolute Paths
- [x] Internet? (2 vids)
- [x] [Code-Along](https://github.com/Hkm9/Acme-Code-Along-) 
- [x] Complete FreeCodeCamp's Applied Accessibility challenges.
![Screenshot 2020-01-14 at 14 58 05](https://user-images.githubusercontent.com/55857486/72441421-f1dd4680-37aa-11ea-92c3-5d75823cb199.png)
- [x] Fork and Clone [HTML-CSS-Practice-Problems](https://github.com/Hkm9/HTML-CSS-Practice-Problems)
- [x] Complete the exercises in ./[level-1](https://github.com/Hkm9/HTML-CSS-Practice-Problems/tree/master/level-1)
- [x] Fork and Clone [css-exercises](https://github.com/Hkm9/css-exercises)
- [x] Turn on GitHub Pages for both of the forks
- [x] Complete [exercise-1](https://github.com/Hkm9/css-exercises/tree/master/exercise-1)
- [x] Complete [exercise-2](https://github.com/Hkm9/css-exercises/tree/master/exercise-2)

**Comment by Hkm9** [comment]
![Screenshot 2020-01-14 at 14 58 05](https://user-images.githubusercontent.com/55857486/72351387-89299780-36e0-11ea-8cb4-d74f495f019d.png)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
