### ISSUE TITLE
shoaib: Week 1, incremental-development

### ISSUE THREAD

**Issue by shoaib-zaheer** [HackYourFutureBelgium/class-7#56]
### Prep Work

- [x] git & github for poets - watch through 1.4
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits
****
### User Stories

- [x] Agile Development by Cartoon
* What is Agile 
        * Agile Manifesto (Value left more then right)
        * 12 Principal
        * Agile Principles & Values
        * Practices
- [x] Splitting User Stories
* Agile Principles
         *
- [x] The "what" not the "how"
****
### Relative Vs. Absolute paths
- [x] Relative vs absolute paths

### Internet?
- [x] How the Internet works in 5 Minutes
- [x] How do Web Browsers work?
- [x] Sign in to FreeCodeCamp using your GitHub account:
    Complete all 22 of FreeCodeCamp's Applied Accessibility challenges.
    Turn on your public portfolio so we can give feedback on your code
****
- [repository](https://github.com/shoaib-zaheer/acme-web-design)
- [live demo](https://shoaib-zaheer.github.io/acme-web-design)
- [x]  [Step/ Commit 1](https://github.com/shoaib-zaheer/acme-web-design/commit/34dc790843fad2ceb8d01f4e271ef93c9995a3c8)
- [x]  [Step/ Commit 2](https://github.com/shoaib-zaheer/acme-web-design/commit/a32a0cf4523028732850a711c09ba882ae145f40)
- [x]  [Step/ Commit 3](https://github.com/shoaib-zaheer/acme-web-design/commit/0db4b9560d326424f5272b1457827429b824ba79)
- [x]  [Step/ Commit 4](https://github.com/shoaib-zaheer/acme-web-design/commit/6b4f97a451e0047ce0de61982749cf8f28e6f0c9)
- [x]  [Step/ Commit 5](https://github.com/shoaib-zaheer/acme-web-design/commit/40b3ff108fc38248e16632fa34744a207ddf1009)
- [x]  [Step/ Commit 6](https://github.com/shoaib-zaheer/acme-web-design/commit/5ddbca2dc9b6b3969a28759195f66394a1d80804)
- [x]  [Step/ Commit 7](https://github.com/shoaib-zaheer/acme-web-design/commit/6e3ef3a18acb61496722949ecc4f8ced866bd7c5)
- [x]  [Step/ Commit 8](https://github.com/shoaib-zaheer/acme-web-design/commit/a1da0aeb9e54da337d7fa7f1b0c053064cc80681)

### Exercises:

- [x] Applied Accessibility 22: [FreeCodeCamp](https://www.freecodecamp.org/fcc5b90401d-9dc0-47db-be41-58e4999022f5)
- [x] Css- exercise: [Exercise-1](https://github.com/shoaib-zaheer/css-exercises/tree/master/exercise-1)
- [x] Css- exercise: [Exercise-2](https://github.com/shoaib-zaheer/css-exercises/tree/master/exercise-2)
- [x] HTML-CSS- Practice-Problems: [./level-1(Step's 1, 2, 3)](https://github.com/shoaib-zaheer/HTML-CSS-Practice-Problems/tree/master/level-1)

![2020-01-16 20-48-07](https://user-images.githubusercontent.com/59531766/72557921-f89ab500-38a1-11ea-9d37-8cc55e7dc5ec.png)

![2020-01-17 01-37-48](https://user-images.githubusercontent.com/59531766/72574778-8be7e080-38ca-11ea-88e9-648463a631e0.png)

![Screenshot from 2020-01-22 02-15-10](https://user-images.githubusercontent.com/59531766/72857400-cd5b0000-3cbd-11ea-81a6-f4e7f213553d.png)

![Screenshot from 2020-01-22 15-57-50](https://user-images.githubusercontent.com/59531766/72905216-75111600-3d30-11ea-8783-694e25cefb88.png)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
