### ISSUE TITLE
Rahel: Week 1,Incremental Development 

### ISSUE THREAD

**Issue by Rahela-HYF** [HackYourFutureBelgium/class-7#57]
### Prep Work

- [x] git & github for poets - watch through 1.4
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits

### User Stories:

 - [x]  Agile Development by Cartoon
 - [x]  Splitting User Stories
 - [x]  The "what" not the "how"

### Relative vs. Absolute Paths
 - [x]  relative vs. absolute paths

### Internet?
 - [x]  How the Internet Works in 5 Minutes
 - [x]    How do Web Browsers Work?

### Code Review
 - [x] Take a look through this page from Study

### Project
- [ ] Code-Along
- [x] (github.com/Rahela-HYF/acme-web-design)
- [ ]  Responsive Layout
- [x]  step-1--creating-empty-index
- [x] step-2-adding-containers-to-index
- [x]  step-3-Adding-boxes

### Exercises on  FreeCodeCamp
 - [x] Sign in to FreeCodeCamp using your GitHub account:
      - [ ]  Complete all 22 of FreeCodeCamp's Applied Accessibility challenges.
      - [x]  Turn on your public portfolio so we can give feedback on your code
  ### Exercises on  forking & cloning repositories 
 - [ ] Fork and Clone HTML-CSS-Practice-Problems:
      - [ ]   Turn on GitHub Pages
      - [ ]   Complete the exercises in ./level-1
   
 - [ ]  Fork and Clone css-exercises
      - [ ]   Turn on GitHub Pages
      - [ ]   Complete exercise-1 and exercise-2

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
