### ISSUE TITLE
Nick: week 2 - incremental development

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#62]
### app-theme:

- [x] [repository](https://github.com/NickMarinade/app-theme)
- [x] [live demo](https://nickmarinade.github.io/app-theme/)
- [History in commits step per step](https://github.com/NickMarinade/app-theme/commits/master?before=0de78657e20714182f4ce97371511b774f03f52c+35)

### Exercises:

- [x] FreeCodeCamp's Responsive Web Design Principles: (https://www.freecodecamp.org/mykola_marenich)
![Безымянный](https://user-images.githubusercontent.com/59340748/73026730-43807380-3e32-11ea-9b91-1ffcc1143ea8.jpg)

- [x] HTML-CSS-Practice-Problems: level-2: [repo](https://github.com/NickMarinade/HTML-CSS-Practice-Problems/tree/master/level-2), [live](https://nickmarinade.github.io/HTML-CSS-Practice-Problems/level-2/) **ask-on-sunday**
- [ ] [css-exercises repo](https://github.com/NickMarinade/css-exercises) 
- [x] exercise-3 [live](https://nickmarinade.github.io/css-exercises/exercise-3/) 
- [x] exercise-4 [live](https://nickmarinade.github.io/css-exercises/exercise-4/) **ask-on-sunday**
- [ ] exercise-5

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
