### ISSUE TITLE
Feridun Akyol: Week 2, Incremental Development

### ISSUE THREAD

**Issue by feridunAKYOL** [HackYourFutureBelgium/class-7#63]
#### Inspecting the DOM
- [x] Read through this site
- [x] And practice studying some HTML/CSS here
HTML & CSS
- [x] What is Responsive Design?

### Name of Project: app-theme

- [repository](https://github.com/feridunAKYOL/app-theme)
- [live demo](https://feridunakyol.github.io/app-theme/)
- [x]  [Startpoint/files&folders](https://github.com/feridunAKYOL/app-theme/pull/1/files)
- [x]  [Menubar](https://github.com/feridunAKYOL/app-theme/pull/2/files)
- [x]  [showcaseArea](https://github.com/feridunAKYOL/app-theme/pull/3/files)
- [x]  [sections](https://github.com/feridunAKYOL/app-theme/pull/4/files)
- [x]  [footer](https://github.com/feridunAKYOL/app-theme/pull/5/files)
- [x]  [aboutPage](https://github.com/feridunAKYOL/app-theme/pull/6/files)
- [x]  [services](https://github.com/feridunAKYOL/app-theme/pull/7/files)
- [x]  [contactPage](https://github.com/feridunAKYOL/app-theme/pull/8/files)
- [x]  [responsiveCheck](https://github.com/feridunAKYOL/app-theme/pull/9/files)
### Exercises:

- [x] Complete all 4 of FreeCodeCamp's Responsive Web Design Principles challenges:   
![ ](https://raw.githubusercontent.com/feridunAKYOL/feridunakyol.github.io/master/freecode_Responsive.png)
- [x]  HTML-CSS-Practice-Problems/level-2: [repo](https://github.com/feridunAKYOL/HTML-CSS-Practice-Problems) [LIVE](https://feridunakyol.github.io/HTML-CSS-Practice-Problems/level-2/)
>* [x] step-1
>* [x] step-2
-  **css-exercises:** [repo](https://github.com/feridunAKYOL/css-exercises)
>* [x] exercise-3 [LIVE](https://feridunakyol.github.io/css-exercises/exercise-3/)
>* [x] exercise-4  [LIVE](https://feridunakyol.github.io/css-exercises/exercise-4/)
>* [ ] exercise-5

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
