### ISSUE TITLE
Daria Shtanko: Week 2, Incremental Development

### ISSUE THREAD

**Issue by ShtankoDaria** [HackYourFutureBelgium/class-7#64]
### Prep Work
Inspecting the DOM
- [x] [Read through this site](https://hackyourfuture.be/inspecting-the-dom/)
- [x] [And practice studying some HTML/CSS here
HTML & CSS](https://janke-learning.org/dom-tutor/?snippet=%3C!DOCTYPE%20html%3E%0A%3Chtml%3E%0A%0A%3Chead%3E%0A%20%20%3Cmeta%20charset%3D%27utf-8%27%3E%0A%20%20%3Cstyle%3E%0A%20%20%20%20.container%20%7B%0A%20%20%20%20%20%20display%3A%20flex%3B%0A%20%20%20%20%20%20flex-direction%3A%20column%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20.above%20%7B%0A%20%20%20%20%20%20order%3A%201%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20.below%20%7B%0A%20%20%20%20%20%20order%3A%202%3B%0A%20%20%20%20%7D%0A%20%20%3C%2Fstyle%3E%0A%3C%2Fhead%3E%0A%0A%3Cbody%3E%0A%20%20%3Cdiv%20class%3D%22container%22%3E%0A%20%20%20%20%3Cp%20id%3D%22p-1%22%20class%3D%22below%22%3E%0A%20%20%20%20%20%20first%20p%0A%20%20%20%20%3C%2Fp%3E%0A%20%20%20%20%3Cp%20id%3D%22p-2%22%20class%3D%22above%22%3E%0A%20%20%20%20%20%20second%20p%0A%20%20%20%20%3C%2Fp%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fbody%3E%0A%0A%3C%2Fhtml%3E%0A)
- [x] [What is Responsive Design?](https://www.youtube.com/watch?v=5KGah8bW8GE)

- [x] git & github for poets - watch through 1.4 
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits

### Name of Project:

- [x] [repository](https://github.com/ShtankoDaria/app-theme)
- [x] [live demo](https://shtankodaria.github.io/app-theme/)
- [x]  [Steps description in Development Strategy file](https://github.com/ShtankoDaria/app-theme/blob/master/development-strategy.md)

### Exercises:

- [x] Responsive Web Design Principles : [freecodecamp](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/) 
![image](https://user-images.githubusercontent.com/59530782/72818573-0074a380-3c6c-11ea-953b-86cc2ac81e42.png)

- [x] HTML-CSS-Practice-Problems: [Level 2](https://github.com/ShtankoDaria/HTML-CSS-Practice-Problems/tree/master/level-2) 
- [ ] css-exercises [exercise 3](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-3)
- [x] css-exercises [exercise 4](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-4)
- [x] css-exercises [exercise 5](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-5)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
