### ISSUE TITLE
Boam1994: Week 2, Incremental Developement

### ISSUE THREAD

**Issue by Boam1994** [HackYourFutureBelgium/class-7#66]
### Prep Work

- [x] Read through this site
- [x] And practice studying some HTML/CSS here

### HTML & CSS

- [x] What is Responsive Design?

###Code Review

- [x] Take a look through this page from Study
###Code-Along

- [repository](https://github.com/boam1994/app-theme)
- [live demo](https://user-name.github.io/repo-name)
- [ ]  [step 1](link to branch for version 1)
- [ ]  [step 2](link to branch for version 2)
- [ ]  [step 3](link to branch for version 3)
- [ ]  ...

### Exercises:

- [ ] exercise name: [repo](https://github.com/boam1994/app-theme), [live (if there is)]()
- [ ] ...

> [Follow this link](https://github.com/HackYourFutureBelgium/class-7/issues/66) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
