### ISSUE TITLE
Hakim: Week 2, incremental-development

### ISSUE THREAD

**Issue by Hkm9** [HackYourFutureBelgium/class-7#67]
- [x] Inspecting the DOM
- [x] HTML & CSS (What is Responsive Design?)
- [x] Git, GitHub & GitKraken
- [x] [Code-Along](https://github.com/Hkm9/app-theme)
- [x] Complete FreeCodeCamp's Responsive Web Design Principles challenges
![Screenshot 2020-01-22 at 14 14 24](https://user-images.githubusercontent.com/55857486/72897169-9ae2ee80-3d21-11ea-9889-83b74d469eb0.png)
- [x] Complete the exercises in [./level-2](https://github.com/Hkm9/HTML-CSS-Practice-Problems/tree/master/level-2) in [HTML-CSS-Practice-Problems-repo](https://github.com/Hkm9/HTML-CSS-Practice-Problems)
- [x] Complete exercise [3](https://github.com/Hkm9/css-exercises/tree/master/exercise-3) [4](https://github.com/Hkm9/css-exercises/tree/master/exercise-4) & [5](https://github.com/Hkm9/css-exercises/tree/master/exercise-5) in [css-exercises-repo](https://github.com/Hkm9/css-exercises)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
