### ISSUE TITLE
Ekaterina: Week 2, Incremental Development

### ISSUE THREAD

**Issue by ekaterinaasf** [HackYourFutureBelgium/class-7#68]
### Prep Work

Inspecting the DOM:
- [x] Read through this site (https://hackyourfuture.be/inspecting-the-dom)
- [x] Practice studying some HTML/CSS here (https://janke-learning.org/dom-tutor)

HTML & CSS:
- [x] What is Responsive Design? (https://www.youtube.com/watch?v=5KGah8bW8GE)
- [x] Code review (https://study.hackyourfuture.be/programming/code-review)

Git, GitHub & GitKraken:
- [x] git & github for poets (https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
- [x] LearnGitBranching (https://learngitbranching.js.org/) & video tutorial (https://www.youtube.com/watch?v=dG0ke9vILQM) - complete the first set of exercises
![Screenshot from 2020-01-23 20-11-52](https://user-images.githubusercontent.com/59531760/73015627-aff07800-3e1c-11ea-9505-2f61517389ad.png)

- [x] Familiarize yourself with GitKraken (https://support.gitkraken.com/start-here/interface/)
- [x] Study this example project (https://github.com/hackyourfuturebelgium/built-with-branches)
- [x] Understand how to use Atomic Commits (https://curiousprogrammer.io/blog/how-to-craft-your-changes-into-small-atomic-commits-using-git)

### Code Along

- [repository](github.com/ekaterinaasf/app-theme)
- [live demo](https://www.youtube.com/watch?v=qlA7dputiNc)
- [x]  Create an empty repository called app-theme
- [x]  [navigation](https://github.com/ekaterinaasf/app-theme/tree/navigation) branch
- [x]  [showcase](https://github.com/ekaterinaasf/app-theme/tree/showcase) branch
- [x]  [features](https://github.com/ekaterinaasf/app-theme/tree/features) branch
- [x]  [info](https://github.com/ekaterinaasf/app-theme/tree/info ) branch
- [x]  [company](https://github.com/ekaterinaasf/app-theme/tree/company) branch
- [x]  [about](https://github.com/ekaterinaasf/app-theme/tree/about) branch
- [x]  [services](https://github.com/ekaterinaasf/app-theme/tree/services) branch
- [x]  [contact](https://github.com/ekaterinaasf/app-theme) branch, made it default branch at the end

### Exercises:
- [x] 4 of FreeCodeCamp's Responsive Web Design Principles challenges: (https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/)
![Screenshot from 2020-01-21 16-14-11](https://user-images.githubusercontent.com/59531760/72816887-2187c500-3c69-11ea-9477-dae04ffbf2e4.png)

- [x] HTML-CSS-Practice-Problems, level-2: [repo](https://github.com/ekaterinaasf/HTML-CSS-Practice-Problems/tree/master/level-2)
- [ ] CSS exercise-3 [repo](https://github.com/ekaterinaasf/css-exercises/tree/master/exercise-3)
- [x] CSS exercise-4 [repo](https://github.com/ekaterinaasf/css-exercises/tree/master/exercise-4)
- [x] CSS exercise-5 [repo](https://github.com/ekaterinaasf/css-exercises/tree/master/exercise-5)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
