### ISSUE TITLE
Oscar: working with code, Week 1

### ISSUE THREAD

**Issue by oscarpete** [HackYourFutureBelgium/class-7#7]
- [x] (computer) Software Installations
  - [x] [Chromium](https://download-chromium.appspot.com/), [Firefox](https://www.mozilla.org/en-US/firefox/developer/) or [Brave](https://brave.com/download/): All great browsers with ES6, HTML5 & CSS3 support plus pre-installed, top-knotch developer tools.  Try each one to see what you like best!
  - [x] [Visual Studio Code](https://code.visualstudio.com/download): Like Microsoft Word, but for code ...  and _sooooo_ much better.  After installing VSC, be sure to install these plug-ins:
    - [x] [Markdown Preview Github Styling Custom](https://marketplace.visualstudio.com/items?itemName=dmodalek.markdown-preview-github-styles-custom)
    - [x] [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
    - [x] [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview)
  - [x] [GitKraken](https://www.gitkraken.com/download): A program that will help you master using git.
  - [x] (If you have windows) [Git For Windows](https://gitforwindows.org/): This will allow you to use the same terminal commands & tools as Linux or Mac computers.
- [x] (computer) Start an HYF Directory
- [x] [My bio on the class repo](https://github.com/hackyourfuturebelgium/class-7/blob/master/student-bios/oscarpete.md)
- [x] [Hack My Future](https://github.com/oscarpete/hack-my-future)
- [x] [Markdown Home Page](https://oscarpete.github.io/) - my multi-page markdown home portfolio, live on github pages

**Comment by oscarpete** [comment]
![29665291_414067125685435_8840113666072447836_o](https://user-images.githubusercontent.com/59342211/71979506-2c306c00-321e-11ea-9115-a2e77b0d8316.jpg)

**Comment by colevandersWands** [comment]
Getting there, just two more little things:
* It looks like you wrote your "student-bio" directly in this repository instead of submitting it with a pull request, I wasn't able to find a closed pull request from you.
* In the "hack-my-future" repository there are instructions to create a "learnables" study board, did you do this? I wasn't able to find one
