### ISSUE TITLE
Elisa: Week 2, Incremental Development

### ISSUE THREAD

**Issue by Elisa0045** [HackYourFutureBelgium/class-7#70]
#### Inspecting the DOM
- [x] Read through this site
- [x] And practice studying some HTML/CSS here
HTML & CSS
- [x] What is Responsive Design?

### Name of Project: app-theme

- [repository](https://github.com/Elisa0045/app-theme)
- [live](https://elisa0045.github.io/app-theme/)

Branches:
* [x] [html-layout-flexboxgrid](https://github.com/Elisa0045/app-theme/tree/html-layout-flexboxgrid)
* [x] [Header](https://github.com/Elisa0045/app-theme/tree/header)
* [x] [Showcase Area](https://github.com/Elisa0045/app-theme/tree/showcase-area)
* [x] [Features](https://github.com/Elisa0045/app-theme/tree/features)
* [x] [Info-area](https://github.com/Elisa0045/app-theme/tree/info-area)
* [x] [Contact-info](https://github.com/Elisa0045/app-theme/tree/contact-info)
* [x] [About-page](https://github.com/Elisa0045/app-theme/tree/about-page)
* [x] [Services-page](https://github.com/Elisa0045/app-theme/tree/services-page)
* [x] [Contact-page](https://github.com/Elisa0045/app-theme/tree/contact-page)
* [x] [Styling-header](https://github.com/Elisa0045/app-theme/tree/styling-header)
* [x] [Styling-showcase](https://github.com/Elisa0045/app-theme/tree/styling-showcase)
* [x] [Media-queries](https://github.com/Elisa0045/app-theme/tree/media-queries)
* [x] [Features-styling](https://github.com/Elisa0045/app-theme/tree/features-styling)
* [x] [Info-styling](https://github.com/Elisa0045/app-theme/tree/info-styling)
* [x] [Styling-company](https://github.com/Elisa0045/app-theme/tree/styling-comany)
* [x] [Styling-footer](https://github.com/Elisa0045/app-theme/tree/styling-footer)
* [x] [Styling-about](https://github.com/Elisa0045/app-theme/tree/styling-about)
* [x] [Styling-services](https://github.com/Elisa0045/app-theme/tree/styling-services)
* [x] [Styling-contact](https://github.com/Elisa0045/app-theme/tree/styling-contact)
* [x] [Update Readme](https://github.com/Elisa0045/app-theme/tree/update%3Dreadme)
* [x] [Header-fix](https://github.com/Elisa0045/app-theme/tree/header-fix)

### Exercises:

- [ ] Complete all 4 of FreeCodeCamp's Responsive Web Design Principles challenges:   

- [ ]  HTML-CSS-Practice-Problems/level-2: 
>* [ ] step-1
>* [ ] step-2
-  **css-exercises:**
>* [ ] exercise-3
>* [ ] exercise-4
>* [ ] exercise-5

> [Follow this link] to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
