### ISSUE TITLE
Daria Shatnko: Week 2, Incremental Development, Wednesday check-in

### ISSUE THREAD

**Issue by ShtankoDaria** [HackYourFutureBelgium/class-7#72]
### Prep Work

- [x] git & github for poets - watch through 1.4 
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits

### Name of Project:

- [x] [repository](https://github.com/ShtankoDaria/app-theme)
- [x] [live demo](https://shtankodaria.github.io/app-theme/)
- [x]  [Steps description in Development Strategy file](https://github.com/ShtankoDaria/app-theme/blob/master/development-strategy.md)

### Exercises:

- [x] Responsive Web Design Principles : [freecodecamp](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/) 
![image](https://user-images.githubusercontent.com/59530782/72818573-0074a380-3c6c-11ea-953b-86cc2ac81e42.png)

- [x] HTML-CSS-Practice-Problems: [Level 2](https://github.com/ShtankoDaria/HTML-CSS-Practice-Problems/tree/master/level-2) 

Now working on css-exercises:

- [x] css-exercises [exercise 3](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-3)
- [x] css-exercises [exercise 4](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-4)
- [x] css-exercises [exercise 5](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-5)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
