### ISSUE TITLE
Daria Shtanko: incremental development, Week 2

### ISSUE THREAD

**Issue by ShtankoDaria** [HackYourFutureBelgium/class-7#73]
Blocked with this exercise, I tried different options but can't manage to make the pictures moving. They just stay in one line. Completely lost  :)

 [ ] css-exercises [exercise 3](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-3)

**Comment by Hkm9** [comment]
you should specify a width and height for the container the is holding the images to be scrolled down.

.scroll{
  width: 35%;
  height:100vh;
  float:left;
  background-color:#404040;
  padding:10px 10px 10px 10px;
  overflow: scroll;
}

Hope that helps ....

**Comment by ShtankoDaria** [comment]
Thanks!
