### ISSUE TITLE
Yared: Week 2, IncrimentalDevelopment

### ISSUE THREAD

**Issue by yaredyilma** [HackYourFutureBelgium/class-7#75]
### Prep Work

- [x] one prep topic
- [x] the next prep topic

### Name of Project:

- [repository](github.com/user-name/repo-name)
- [live demo](https://yaredyilma.github.io/app-theme2/index.html)
- [x] [ step 1](https://github.com/yaredyilma/app-theme2/pull/1)
- [x] [ step 2](https://github.com/yaredyilma/app-theme2/pull/2)
- [x]  [step 3](https://github.com/yaredyilma/app-theme2/pull/3)
- [x]  [step 4](https://github.com/yaredyilma/app-theme2/pull/4)
- [x]  [step 5](https://github.com/yaredyilma/app-theme2/pull/5)
- [x]  [ step 6](https://github.com/yaredyilma/app-theme2/pull/6)
- [x]  [ step 7](https://github.com/yaredyilma/app-theme2/pull/7)

### Exercises:
- [x] exercise name: (https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/create-a-media-query)
- [ ] exercise name: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
- [ ] exercise name: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
- [ ] ...

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
