### ISSUE TITLE
Hakim: Week 3, Incremental Development

### ISSUE THREAD

**Issue by Hkm9** [HackYourFutureBelgium/class-7#76]
- [x] Accessibility
- [x] WireFrames
- [x] Git, GitHub & GitKraken
- [x] Home page clone of [DuckDuckGo](https://github.com/Hkm9/duck-duck-clone)  | [LiveDemo](https://hkm9.github.io/duck-duck-clone/)
- [x] HTML-CSS-Practice-Problems ./[level-3](https://github.com/Hkm9/HTML-CSS-Practice-Problems/tree/master/level-3)
- [x] css-exercises exercise [6](https://github.com/Hkm9/css-exercises/tree/master/exercise-6) & [8](https://github.com/Hkm9/css-exercises/tree/master/exercise-8)
- [x] Fork & Clone [html-css-git-exercises](https://github.com/Hkm9/html-css-git-exercises) | [week1](https://github.com/Hkm9/html-css-git-exercises/tree/master/week-1)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
