### ISSUE TITLE
Oscar: Week 2- Incremental Development

### ISSUE THREAD

**Issue by oscarpete** [HackYourFutureBelgium/class-7#77]
### Prep Work

- [x] Read through this site
- [x] And practice studying some HTML/CSS here
- [x] What is Responsive Design?

### app-theme:

- [x] [repository](https://github.com/oscarpete/app-theme)
- [x] [live demo](https://oscarpete.github.io/app-theme/)
- [x] History in commits step per step](https://github.com/oscarpete/app-theme/branches)

### Exercises:

- [x] FreeCodeCamp's Responsive Web Design Principles: (https://www.freecodecamp.org/oscarpete)

- [ ] HTML-CSS-Practice-Problems: level-2: [repo](https://github.com/oscarpete/HTML-CSS-Practice-Problems/tree/master/level-2), [live](https://oscarpete.github.io/HTML-CSS-Practice-Problems/level-2/)
- [ ] ...

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
