### ISSUE TITLE
mhammadmusa: Incremental Development - Week 1

### ISSUE THREAD

**Issue by mhammadmusa** [HackYourFutureBelgium/class-7#78]
### Pre Work

- [x] [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV) - watch through 1.4
- [x] [LearnGitBranching & video tutorial](https://learngitbranching.js.org/) - [complete the first set of exercises](https://www.youtube.com/watch?v=dG0ke9vILQM) -  complete the first set of exercises
- [x] [Familiarize yourself with GitKraken](https://support.gitkraken.com/start-here/interface/) 
- [x] [Study this example project](https://github.com/hackyourfuturebelgium/built-with-branches)
- [x] [Understand how to use Atomic Commits](https://curiousprogrammer.io/blog/how-to-craft-your-changes-into-small-atomic-commits-using-git) 

### User Stories
- [ ] [Agile Development by Cartoon](https://www.youtube.com/watch?v=Z9QbYZh1YXY&list=PLBUu5aGDLKnbeEx8U-5r436bw6p9wv1rS)
- [ ] [Splitting User Stories](https://www.youtube.com/watch?v=EDT0HMtDwYI)
- [ ] [The "what" not the "how"](https://duckduckgo.com/?q=what+are+user+stories&t=brave&iax=videos&ia=videos&iai=Pn-QMvDTuEY)

### Relative vs. Absolute Paths

- [ ] [relative vs. absolute paths](https://www.youtube.com/watch?v=ephId3mYu9o)

### Internet?
- [ ] [How the Internet Works in 5 Minutes](https://www.youtube.com/watch?v=7_LPdttKXPc)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
