### ISSUE TITLE
Nour: Week 2, Incremental development

### ISSUE THREAD

**Issue by nouralkurd** [HackYourFutureBelgium/class-7#79]
### Prep Work
**Inspecting the DOM**
- [x] [Read through this site](https://hackyourfuture.be/inspecting-the-dom)
- [x] [And practice studying some HTML/CSS here](https://janke-learning.org/dom-tutor)

**HTML & CSS**

- [x] [What is Responsive Design?]( https://www.youtube.com/watch?v=5KGah8bW8GE)

**Code Review**

- [x] [Take a look through this page from Study](https://study.hackyourfuture.be/programming/code-review)

**Git, GitHub & GitKraken**
 - [x] [git & github for poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
 - [x] [LearnGitBranching](https://learngitbranching.js.org/)
 - [x] [Familiarize yourself with GitKraken](https://support.gitkraken.com/start-here/interface/)
 - [x] [Study this example project](https://github.com/hackyourfuturebelgium/built-with-branches)
- [x] [Understand how to use Atomic Commits](https://curiousprogrammer.io/blog/how-to-craft-your-changes-into-small-atomic-commits-using-git)

### Name of Project:

- [repository](https://github.com/nouralkurd/app-theme/commit/667a5f1776bf226bdde77cadcb39640f41112f5b)
- [live demo](https://user-name.github.io/repo-name)

### Exercises:

- [ ] exercise name: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
- [ ] exercise name: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
- [ ] ...

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
