### ISSUE TITLE
Shoaib: working with code, Week 1

### ISSUE THREAD

**Issue by shoaib-zaheer** [HackYourFutureBelgium/class-7#8]
- [x] (computer) Software Installations
  - [x] [Chromium](https://download-chromium.appspot.com/), [Firefox](https://www.mozilla.org/en-US/firefox/developer/) or [Brave](https://brave.com/download/): All great browsers with ES6, HTML5 & CSS3 support plus pre-installed, top-knotch developer tools.  Try each one to see what you like best!
  - [x] [Visual Studio Code](https://code.visualstudio.com/download): Like Microsoft Word, but for code ...  and _sooooo_ much better.  After installing VSC, be sure to install these plug-ins:
    - [x] [Markdown Preview Github Styling Custom](https://marketplace.visualstudio.com/items?itemName=dmodalek.markdown-preview-github-styles-custom)
    - [x] [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
    - [x] [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview)
  - [x] [GitKraken](https://www.gitkraken.com/download): A program that will help you master using git.
  - [x] (If you have windows) [Git For Windows](https://gitforwindows.org/): This will allow you to use the same terminal commands & tools as Linux or Mac computers.
- [x] (computer) Start an HYF Directory
- [x] [My bio on the class repo](https://github.com/hackyourfuturebelgium/class-7/blob/master/student-bios/Shoaib-Zaheer.md)
- [x] [Hack My Future](https://github.com/shoaib-zaheer/hack-my-future)
- [x] [Markdown Home Page](https://shoaib-zaheer.github.io/) - my multi-page markdown home portfolio, live on github pages

**Comment by Hkm9** [comment]
Same Question for me. Do we make the link between (working with code program) and the (bio of ourselves we did) using a pull ? How do we link the two? Thanks ....

**Comment by colevandersWands** [comment]
For the bio, you will need to do a PR.  
1. Fork the class-7 repository if you haven't
1. write your bio on _your_ fork
1. send a pull request to the `hackyourfuturebelgium` fork

For the link in this issue, if you edit it you will see "your-user-name".  replace that with your user name and the link will work ;)

**Comment by colevandersWands** [comment]
> I sent the Template & choose the GitHub Pages/ Source to >Master branch< still can get my page running what should i do more ?
> https://shoaib-zaheer.github.io/ <-- Not working :(

**Comment by colevandersWands** [comment]
> I sent the Template & choose the GitHub Pages/ Source to >Master branch< still can get my page running what should i do more ?
> https://shoaib-zaheer.github.io/ <-- Not working :(

**Comment by colevandersWands** [comment]
change this name of this repository (https://github.com/shoaib-zaheer/github.io) to https://github.com/shoaib-zaheer/shoaib-zaheer.github.io

* https://help.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by shoaib-zaheer** [comment]
![Screenshot 2020-01-07 at 21 46 06](https://user-images.githubusercontent.com/59531766/71928165-470bcd80-3197-11ea-8fa5-e93130b4f0b2.png)


now it is changed to  https://github.com/shoaib-zaheer/shoaib-zaheer.github.io

still it is not working/ do I make other mistake, I am attaching the screen shot for 3 different windows to check.
this is the last thing I am stack in it :(

**Comment by colevandersWands** [comment]
GitHub pages will turn the README.md file into your home page.  If there is no README it won't make a website.

Renaming bio.md to README.md should do the trick

**Comment by Hkm9** [comment]
Change the text in your issue with this one 

- [x] (computer) Software Installations
  - [x] [Chromium](https://download-chromium.appspot.com/), [Firefox](https://www.mozilla.org/en-US/firefox/developer/) or [Brave](https://brave.com/download/): All great browsers with ES6, HTML5 & CSS3 support plus pre-installed, top-knotch developer tools.  Try each one to see what you like best!
  - [x] [Visual Studio Code](https://code.visualstudio.com/download): Like Microsoft Word, but for code ...  and _sooooo_ much better.  After installing VSC, be sure to install these plug-ins:
    - [x] [Markdown Preview Github Styling Custom](https://marketplace.visualstudio.com/items?itemName=dmodalek.markdown-preview-github-styles-custom)
    - [x] [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
    - [x] [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview)
  - [x] [GitKraken](https://www.gitkraken.com/download): A program that will help you master using git.
  - [x] (If you have windows) [Git For Windows](https://gitforwindows.org/): This will allow you to use the same terminal commands & tools as Linux or Mac computers.
- [x] (computer) Start an HYF Directory
- [x] [My bio on the class repo](https://github.com/hackyourfuturebelgium/class-7/blob/master/student-bios/Hkm9.md)
- [x] [Hack My Future](https://github.com/Hkm9/hack-my-future)
- [ ] [Markdown Home Page](https://Hkm9.github.io) - my multi-page markdown home portfolio, live on github pages

And change the name Hkm9 to your profile name

**Comment by shoaib-zaheer** [comment]
wow thanks a lot @colevandersWands I am done at last

**Comment by colevandersWands** [comment]
🔎 Some nit-picking here.  Still the project board to make in `hack-my-future`

**Comment by shoaib-zaheer** [comment]
Hooo :( Hope this time every thing work as per requirement, waiting for good news :)

**Comment by colevandersWands** [comment]
* the markdown for your student bio is great, but it looks like you didn't add it using a Pull Request. I can tell this because [there are no closed pull requests from you](https://github.com/HackYourFutureBelgium/class-7/pulls?q=is%3Apr+is%3Aclosed), and [your fork does not have your bio](https://github.com/shoaib-zaheer/class-7/tree/master/student-bios)
* Still no project board in your `hack-my-future` - https://github.com/shoaib-zaheer/hack-my-future/projects

Getting there!  This is a tricky homework with lots of little details

**Comment by colevandersWands** [comment]
Nailed it ⚒

**Comment by shoaib-zaheer** [comment]
> i Think i am done with both of miss parts (**HOPE SS**) :disappointed:
