### ISSUE TITLE
Ekaterina: Week 3, Incremental Development

### ISSUE THREAD

**Issue by ekaterinaasf** [HackYourFutureBelgium/class-7#80]
### Prep Work

Accessibility:
- [x] ARIA landmark roles (https://www.youtube.com/watch?v=o4xHfi4t9S0&list=PLWjCJDeWfDdcEtSnqq_iGLKGA_H_3o3y7)
- [x] Empathy Prompts (https://empathyprompts.net/)

WireFrames:
- [x] What are these things? (https://www.youtube.com/results?search_query=what+are+wireframes)
- [x] Why are these so great? (https://medium.com/@ray_vevaina/wireframing-a-front-end-developers-best-friend-c541df51ea65)
- [x] wireframe.cc - online wireframes (https://wireframe.cc/)

### Code Along

- [repository](https://github.com/ekaterinaasf/duck-duck-clone)
- [Example Duck Duck Go homepage](https://duckduckgo.com/)
- [x]  [README.md](https://github.com/ekaterinaasf/duck-duck-clone/blob/search/README.md)
- [x]  [development-strategy.md](https://github.com/ekaterinaasf/duck-duck-clone/blob/master/development-strategy.md)
- [x]  [master](https://github.com/ekaterinaasf/duck-duck-clone/) branch
- [x]  [header](https://github.com/ekaterinaasf/duck-duck-clone/tree/header) branch
- [x]  [search](https://github.com/ekaterinaasf/duck-duck-clone/tree/search) branch
- [ ]  [images](https://github.com/ekaterinaasf/duck-duck-clone/tree/images) branch

### Exercises:
- [x] HTML-CSS-Practice-Problems, level-3: [repo](https://github.com/ekaterinaasf/HTML-CSS-Practice-Problems/tree/master/level-3)
- [x] CSS exercise-6 [repo](https://github.com/ekaterinaasf/css-exercises/tree/master/exercise-6)
- [x] CSS exercise-8 [repo](https://github.com/ekaterinaasf/css-exercises/tree/master/exercise-8)
- [ ] html-css-git-exercises [repo](https://github.com/ekaterinaasf/html-css-git-exercises)

> [Follow this link](https://github.com/HackYourFutureBelgium/incremental-development/tree/master/week-3) to study a well-done homework issue for week 3.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
