### ISSUE TITLE
Shoaib: Week 3, Incremental Development

### ISSUE THREAD

**Issue by shoaib-zaheer** [HackYourFutureBelgium/class-7#81]
### Accessibility
- [x] ARIA landmark roles
- [x] Finding which colors a website uses
- [x] Which fonts a website uses
- [x] Which images a website uses

### Wire Frames
- [x] What are these things? [`Video`](https://www.youtube.com/watch?v=T0vt3nLZKks)
- [x] Why are these so great? [`Video`](https://www.youtube.com/watch?v=JcTxP1Y9nWc)
- [x] wireframe.cc - online wireframes

### HomeWork *(DUCK-DUCK)*

**DUCK-DUCK-clone** [`Repository`](https://github.com/shoaib-zaheer/duck-duck-clone)
**Theme** [`Live-Demo`](https://shoaib-zaheer.github.io/duck-duck-clone/)

### Exercises:

- [ ] CSS exercise: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
- [ ] CSSexercise: [repo](https://github.com/user-name/repo-name), [live (if there is)]()

![duckduckwireframe](https://user-images.githubusercontent.com/59531766/73141787-61471600-4088-11ea-986d-b4b0978eb682.png)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
