### ISSUE TITLE
Feridun Akyol: Week 3, Incremental Development

### ISSUE THREAD

**Issue by feridunAKYOL** [HackYourFutureBelgium/class-7#82]
#### Accessibility
- [x] ARIA landmark roles
- [x] Empathy Prompts
#### WireFrames
- [x] What are these things?
- [x] Why are these so great?
- [x] wireframe.cc - online wireframes

### DuckDuckGo home page:

- [repository](https://github.com/feridunAKYOL/duck-duck-clone)
- [live demo](https://feridunakyol.github.io/duck-duck-clone/)
- [x]  [startingPoint/Files/DevelopmentStrategy](https://github.com/feridunAKYOL/duck-duck-clone/pull/1)
- [x]  [SideMenu](https://github.com/feridunAKYOL/duck-duck-clone/pull/2/files)
- [x]  [section-1](https://github.com/feridunAKYOL/duck-duck-clone/pull/3/files)
- [x]  [section-2](https://github.com/feridunAKYOL/duck-duck-clone/pull/4/files)
- [x]  [section-3](https://github.com/feridunAKYOL/duck-duck-clone/pull/5/files)
- [x]  [section-4](https://github.com/feridunAKYOL/duck-duck-clone/pull/6/files)
- [x]  [section-5](https://github.com/feridunAKYOL/duck-duck-clone/pull/7/files)
- [x]  [menubarfixed](https://github.com/feridunAKYOL/duck-duck-clone/pull/8/files)

### Exercises:

- HTML-CSS-Practice-Problems
>>- [x] level-3 : [repo](https://github.com/feridunAKYOL/HTML-CSS-Practice-Problems), [live](https://feridunakyol.github.io/HTML-CSS-Practice-Problems/level-3/)
- CSS-EXERCISES
>>- [x] css-exercises/ exercise-6: [repo](https://github.com/feridunAKYOL/css-exercises/), [live](https://feridunakyol.github.io/css-exercises/exercise-6/)
>>- [x] css-exercises/ exercise-8: [repo](https://github.com/feridunAKYOL/css-exercises/), [live](https://feridunakyol.github.io/css-exercises/exercise-8/)
- HTML-CSS-GIT-exercises
>>- [x] exercises  
- [x] Extra challenge :fire:

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
