### ISSUE TITLE
mhammadmusa: Incremental Development - Week 3

### ISSUE THREAD

**Issue by mhammadmusa** [HackYourFutureBelgium/class-7#83]

**Comment by mhammadmusa** [comment]
### Prep Work
---

- [ ] [ARIA landmark roles](https://www.youtube.com/watch?v=js9yaVtV04E&list=PLWjCJDeWfDdcEtSnqq_iGLKGA_H_3o3y7&index=4)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
