### ISSUE TITLE
Nick: Week 3, Incremental Development 

### ISSUE THREAD

**Issue by NickMarinade** [HackYourFutureBelgium/class-7#84]
### Prep Work

- [x] ARIA landmark roles
- [x] Empathy Prompts
- [x] WireFrames

### Clone of the DuckDuckGo home page.
 
- [x] [repository](https://github.com/NickMarinade/duck-duck-clone)
- [x] [live demo](https://nickmarinade.github.io/duck-duck-clone/)
- [x] [Prep](https://github.com/NickMarinade/duck-duck-clone/tree/Prep)
- [x]  [Header](https://github.com/NickMarinade/duck-duck-clone/tree/header)
- [x]  [Showcase](https://github.com/NickMarinade/duck-duck-clone/tree/showcase)
- [x]  [Info](https://github.com/NickMarinade/duck-duck-clone/tree/info)
- [x]  [Headercss](https://github.com/NickMarinade/duck-duck-clone/tree/headercss)
- [x]  [Showcasecss](https://github.com/NickMarinade/duck-duck-clone/tree/showcasecss)
- [x]  [Infocss](https://github.com/NickMarinade/duck-duck-clone/tree/infocss)

### Exercises:

- [ ] HTML-CSS-Practice-Problems: [Level 3]() 
- [x] css-exercises [exercise 6 branch]https://github.com/NickMarinade/css-exercises/tree/ex6)
[live](https://nickmarinade.github.io/css-exercises/exercise-6/)
- [ ] css-exercises [exercise 8]()
- [ ] [html-css-git-exercises]()

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
