### ISSUE TITLE
ShtankoDaria: Week 3, Incremental Development

### ISSUE THREAD

**Issue by ShtankoDaria** [HackYourFutureBelgium/class-7#85]
### Prep Work
Accessibility
- [x] [ARIA landmark roles]
- [x] [Empathy Prompts]

WireFrames
- [x] [What are these things?]
- [x] [Why are these so great?]
- [x] [wireframe.cc - online wireframes]

Git, GitHub & GitKraken
This module's main objective is to learn how Git & GitHub can be used to organize your development process. Come prepared for Sunday's activities by studying these links:

- [x] git & github for poets
- [x] LearnGitBranching & video tutorial - complete the first set of exercises
- [x] Familiarize yourself with GitKraken
- [x] Study this example project
- [x] Understand how to use Atomic Commits

### Name of Project:

- [repository](https://github.com/ShtankoDaria/duck-duck-clone)
- [live demo](https://shtankodaria.github.io/duck-duck-clone/)
- [development strategy](https://github.com/ShtankoDaria/duck-duck-clone/blob/master/development-strategy.md)

### Exercises:

- [ ] HTML-CSS-Practice-Problems: [Level 3](https://github.com/ShtankoDaria/HTML-CSS-Practice-Problems/tree/master/level-3) 
- [x] css-exercises [exercise 6](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-6)
- [ ] css-exercises [exercise 8](https://github.com/ShtankoDaria/css-exercises/tree/master/exercise-8)
- [ ] [html-css-git-exercises] (https://github.com/ShtankoDaria/html-css-git-exercises)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
