### ISSUE TITLE
Elisa: Week 3, Incremental Development 

### ISSUE THREAD

**Issue by Elisa0045** [HackYourFutureBelgium/class-7#87]
### Prep Work
- [x] Accessibility
 - [x] ARIA landmark roles
 - [x] Empathy Prompts

 - [x] WireFrames
 - [x] What are these things?
- [x]  Why are these so great?

## DuckDuckGo clone
   - [repository](https://github.com/Elisa0045/duck-duck-clone)
   - [live demo](https://elisa0045.github.io/duck-duck-clone/)

Step by step: Branches.
* [x] [Header](https://github.com/Elisa0045/duck-duck-clone/tree/header)
* [x] [Main-Search-Area](https://github.com/Elisa0045/duck-duck-clone/tree/main-search-area)
* [x] [Feature-1](https://github.com/Elisa0045/duck-duck-clone/tree/feature-1)
* [x] [Feature-2](https://github.com/Elisa0045/duck-duck-clone/tree/feature-2)
* [x] [Feature-3](https://github.com/Elisa0045/duck-duck-clone/tree/feature-3)
* [x] [Feature-4](https://github.com/Elisa0045/duck-duck-clone/tree/feature-4)
* [x] [Readme](https://github.com/Elisa0045/duck-duck-clone/tree/readme)

### Exercises

There are 3 sets of exercises to start (and probably not finish, there's a lot this week).

* In [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems):
  - [ ]   Turn on GitHub Pages
  - [ ]   Complete the exercises in `./level-3`
  - [ ]   Push your work regularly, so you can ask questions with issues!
* In [css-exercises](https://github.com/dangodev/css-exercises)
  - [ ]   Turn on GitHub Pages
  - [ ]   Complete `exercise-6` and `exercise-8`
  - [ ]   Push your work regularly, so you can ask questions with issues!
* Fork & Clone [html-css-git-exercises](https://github.com/CodeYourFuture/html-css-git-exercises)
  - [ ]   Turn on GitHub Pages

* Begin the exercises.  There is no specific assignment, just a lot more practice available to keep your HTML/CSS sharp throughout the next modules
* Push your work regularly, so you can ask questions with issues!

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
