### ISSUE TITLE
Boam1994: Week 3, Incremental Development

### ISSUE THREAD

**Issue by Boam1994** [HackYourFutureBelgium/class-7#89]
### Prep Work

- [x] ARIA landmark roles
- [x] Empathy Prompts

 ### WireFrames
- [x] What are these things?
- [x]  Why are these so great?
- [x] wireframe.cc - online wireframes

### Open-Ended

###Clone duck-duck-clone
- [repository](github.com/user-name/repo-name)
- [live demo](https://user-name.github.io/repo-name)

- [ ]  [step 1](link to branch for version 1)
- [ ]  [step 2](link to branch for version 2)
- [ ]  [step 3](link to branch for version 3)
- [ ]  ...

### Exercises:

- [ ] exercise name: [repo](https://github.com/user-name/repo-name), [live (if there is)]()
- [ ] ...

> [Follow this link](https://github.com/HackYourFutureBelgium/class-7/issues/89) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
