### ISSUE TITLE
Rahel: Week 3, Increamental Development

### ISSUE THREAD

**Issue by Rahela-HYF** [HackYourFutureBelgium/class-7#91]
### Prep Work

 Accessibility
- [ ] ARIA landmark roles
- [ ]  Empathy Prompts

WireFrames
- [ ]  What are these things?
- [ ]  Why are these so great?
- [ ]  wireframe.cc - online wireframes

### duck-duck-clone
- [ ]  [step 1](link to branch for version 1)
- [ ]  [step 2](link to branch for version 2)
- [ ]  [step 3](link to branch for version 3)
- [ ]  ...

##  HTML-CSS-Practice-Problems:
- [ ]  Complete the exercises in ./level-3
## CSS-exercises 
- [ ]  Complete exercise-6 and exercise-8
- [ ]  Fork & Clone html-css-git-exercises

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
