### ISSUE TITLE
Oscar: Week 3, Incremental Development

### ISSUE THREAD

**Issue by oscarpete** [HackYourFutureBelgium/class-7#92]
#### Accessibility
- [ ] ARIA landmark roles
- [ ] Empathy Prompts
#### WireFrames
- [ ] What are these things?
- [ ] Why are these so great?
- [ ] wireframe.cc - online wireframes

### DuckDuckGo home page:

- [repository](https://github.com/oscarpete/duck-duck-clone)
- [live demo](https://oscarpete.github.io/duck-duck-clone/)
- [ ]  [startingPoint/Files/DevelopmentStrategy](https://github.com/oscarpete/duck-duck-clone/)
- [ ]  [SideMenu](https://github.com/oscarpete/duck-duck-clone/)

### Exercises:

- HTML-CSS-Practice-Problems
>>- [ ] level-3 : [repo](https://github.com/feridunAKYOL/HTML-CSS-Practice-Problems), [live](https://feridunakyol.github.io/HTML-CSS-Practice-Problems/level-3/)
- CSS-EXERCISES
>>- [ ] css-exercises/ exercise-6: [repo](https://github.com/oscarpete/css-exercises/), [live](https://oscarpete.github.io/css-exercises/exercise-6/)
>>- [ ] css-exercises/ exercise-8: [repo](https://github.com/oscarpete/css-exercises/), [live](https://oscarpete.github.io/css-exercises/exercise-8/)
- HTML-CSS-GIT-exercises

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
