### ISSUE TITLE
Yared Yilma: Week 3, Incremental Development

### ISSUE THREAD

**Issue by yaredyilma** [HackYourFutureBelgium/class-7#93]
### Prep Work

- [x] Accessibility
 - [x] ARIA landmark roles
 - [x] Empathy Prompts

 - [x] WireFrames
 - [x] What are these things?
- [x]  Why are these so great?

### Name of Project:

DuckDuckGo clone
- [x] [Repository](https://github.com/yaredyilma/duck-duck-clone/blob/master/index.html)
[live demo](https://yaredyilma.github.io/duck-duck-clone/)

### Exercises:

* In [HTML-CSS-Practice-Problems](https://github.com/DevMountain/HTML-CSS-Practice-Problems):
  - [x]   Turn on GitHub Pages
  - [x]   Complete the exercises in `./level-3`
  - [x]   Push your work regularly, so you can ask questions with issues!

* In [css-exercises](https://github.com/dangodev/css-exercises)
  - [ ]   Turn on GitHub Pages
  - [ ]   Complete `exercise-6` and `exercise-8`
  - [ ]   Push your work regularly, so you can ask questions with issues!

* Fork & Clone [html-css-git-exercises](https://github.com/CodeYourFuture/html-css-git-exercises)
  - [ ]   Turn on GitHub Pages

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
