### ISSUE TITLE
Feridun Akyol: Week 1, Separation of Concerns

### ISSUE THREAD

**Issue by feridunAKYOL** [HackYourFutureBelgium/class-7#96]
#### What is JavaScript?
>- [x] Andrew Mosh
>- [x] Code School
>- [x] MDN: First Steps
>- [x] MDN: JS Basics
>- [x] javascript.info
#### Write some Code
>- [x] Including JS in HTML
>- [x] Using JS DevTools
>- [x] Rules for writing JS
>- [x] Start learnjavascript.online through 2. Strings

### Project: calculator-refactor

- [repository](https://github.com/feridunAKYOL/calculator-refactor)
- [live demo](https://feridunakyol.github.io/calculator-refactor/)
- [x]  [DOM](https://github.com/feridunAKYOL/calculator-refactor/pull/1/files)
- [x]  [styles](https://github.com/feridunAKYOL/calculator-refactor/pull/2/files)
- [x]  [listener](https://github.com/feridunAKYOL/calculator-refactor/pull/3/files)
- [x]  [handler](https://github.com/feridunAKYOL/calculator-refactor/pull/5/files)
- [x]  [logic](https://github.com/feridunAKYOL/calculator-refactor/pull/6/files)

### Exercises:
1. #### using-user-input
>- [x] Turn on GitHub Pages
>- [x] Complete 1-fill-in-the-blanks [live](https://feridunakyol.github.io/using-user-input/)
>- [x] Push your work regularly 
2. #### FreeCodeCamp JavaScript exercises 
>- [x] Sign into FreeCodeCamp 
>- [x] Turn on your Public Profile
>- [x] Complete Basic JavaScript up through Golf Code  
![](https://raw.githubusercontent.com/feridunAKYOL/feridunakyol.github.io/freeCode/screencapture-freecodecamp-org-learn-2020-02-05-23_34_47.png)
>- [ ] Copy-paste each and every exercise into JS Tutor to get the most out of your studying!
3. #### Continue studying the exercises from in class
>- [x] study them live in the lesson plan 
>- [x] clone this repository and try run the source files in Node.js
>- [ ] study the exercises in JS Tutor and practice them

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by inglkruiz** [comment]
Hi, you need to move your logic developed in `calculator` function to the `doMath` function. For us is important to run your logic against the test cases.
