### ISSUE TITLE
Oscar: Week 4, Separation of Concerns

### ISSUE THREAD

**Issue by oscarpete** [HackYourFutureBelgium/class-7#97]
#### What is JavaScript?
>- [x] Andrew Mosh
>- [x] Code School
>- [x] MDN: First Steps
>- [x] MDN: JS Basics
>- [x] javascript.info
#### Write some Code
>- [x] Including JS in HTML
>- [x] Using JS DevTools
>- [x] Rules for writing JS
>- [x] Start learnjavascript.online through 2. Strings

### Project: calculator-refactor

- [repository](github.com/oscarpete/calculator-refactor)
- [live demo](https://oscarpete.github.io/calculator-refactor/)
- [x]  [Dom](https://github.com/oscarpete/calculator-refactor/tree/DOM)
- [x]  [Styles](https://github.com/oscarpete/calculator-refactor/tree/style)
- [x]  [listener](https://github.com/oscarpete/calculator-refactor/tree/listener)
- [x]  [handler](https://github.com/oscarpete/calculator-refactor/tree/handler)
- [x]  [logic](https://github.com/oscarpete/calculator-refactor/tree/oscarpete-patch-1)

### Exercises:
1. #### using-user-input
>- [x] Turn on GitHub Pages
>- [ ] Complete 1-fill-in-the-blanks
>- [ ] Push your work regularly 
2. #### FreeCodeCamp JavaScript exercises 
>- [x] Sign into FreeCodeCamp 
>- [x] Turn on your Public Profile
>- [x] [Complete Basic JavaScript up through Golf Code](https://www.freecodecamp.org/oscarpete)

3. #### Continue studying the exercises from in class
>- [ ] study them live in the lesson plan 
>- [ ] clone this repository and try run the source files in Node.js
>- [ ] study the exercises in JS Tutor and practice them

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by oscarpete** [comment]
What is the difference between "pop" and [] ??

**Comment by oscarpete** [comment]
on this example:
function equalityTest(myVal) {
  if (myVal == 10) {
     return "Equal";
  }
  return "Not Equal";
}

Why they didnt use "else"???????

**Comment by oscarpete** [comment]
on this:
1 != true   // false
0 != false  // false

It shoudln't be true?????

**Comment by oscarpete** [comment]
I dindt get it about the golf
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-golf-code/18195

I have to ask

**Comment by oscarpete** [comment]
also this one
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-stand-in-line/18307

**Comment by NickMarinade** [comment]
> on this:
> 1 != true // false
> 0 != false // false
> 
> It shoudln't be true?????

1 is not true ( false, 'cause 1 is true)
0 is not false ( false, 'cause 0 is false)
Something like that)

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
