### ISSUE TITLE
Hakim: Week 1, Separation of Concerns

### ISSUE THREAD

**Issue by Hkm9** [HackYourFutureBelgium/class-7#99]
- [x] What is JavaScript
- [x] Write some Code
- [x] Project: [calculator-refactor](https://github.com/Hkm9/calculator-refactor) | [live-demo](https://hkm9.github.io/calculator-refactor/)
- [x] Fork [using-user-input](https://github.com/Hkm9/using-user-input) and Complete [1-fill-in-the-blanks](https://github.com/Hkm9/using-user-input/tree/master/1-fill-in-the-blanks)
- [x] Begin the FreeCodeCamp JavaScript exercises until Golf Code
![Screenshot 2020-02-06 at 14 25 03](https://user-images.githubusercontent.com/55857486/73941021-c7cffd80-48ec-11ea-9125-bf71111f1bb1.png)
- [x] Continue studying the exercises from class

**Comment by dfdeagle47** [comment]
Cleaning up old issues.
